### ISSUE TITLE
Linux GTK integration build error

### ISSUE THREAD

**Issue by reagentoo** [telegramdesktop/tdesktop#10213]
### Steps to reproduce
1. Build tdesktop
2. 
3. 

**Logs**:
```
/var/tmp/portage/net-im/telegram-desktop-2.5.6/work/tdesktop-2.5.6-full/Telegram/SourceFiles/platform/linux/linux_gtk_integration.cpp:331:3: error: assigning to 'GdkScreen *(*)(GdkDisplay *)' (aka '_GdkScreen *(*)(_GdkDisplay *)') from incompatible type 'GdkMonitor *(GdkDisplay *)' (aka '_GdkMonitor *(_GdkDisplay *)'): different return type ('GdkScreen *' (aka '_GdkScreen *') vs 'GdkMonitor *' (aka '_GdkMonitor *'))
                LOAD_GTK_SYMBOL(lib_gtk, "gdk_display_get_primary_monitor", gdk_display_get_primary_monitor);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/net-im/telegram-desktop-2.5.6/work/tdesktop-2.5.6-full/Telegram/SourceFiles/platform/linux/linux_gtk_integration_p.h:24:50: note: expanded from macro 'LOAD_GTK_SYMBOL'
#define LOAD_GTK_SYMBOL(lib, name, func) (func = ::func)
                                                 ^~~~~~
/var/tmp/portage/net-im/telegram-desktop-2.5.6/work/tdesktop-2.5.6-full/Telegram/SourceFiles/platform/linux/linux_gtk_integration.cpp:332:3: error: assigning to 'int (*)(GdkScreen *)' (aka 'int (*)(_GdkScreen *)') from incompatible type 'int (GdkMonitor *)' (aka 'int (_GdkMonitor *)'): type mismatch at 1st parameter ('GdkScreen *' (aka '_GdkScreen *') vs 'GdkMonitor *' (aka '_GdkMonitor *'))
                LOAD_GTK_SYMBOL(lib_gtk, "gdk_monitor_get_scale_factor", gdk_monitor_get_scale_factor);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/net-im/telegram-desktop-2.5.6/work/tdesktop-2.5.6-full/Telegram/SourceFiles/platform/linux/linux_gtk_integration_p.h:24:50: note: expanded from macro 'LOAD_GTK_SYMBOL'
#define LOAD_GTK_SYMBOL(lib, name, func) (func = ::func)
                                                 ^~~~~~
2 errors generated.
```

**Comment by noiseless** [comment]
I have the same problem.

**Comment by ilya-fedin** [comment]
I wonder why there's no such errors on CI...

**Comment by ilya-fedin** [comment]
Please check if this fixes the issue
```
diff --git a/Telegram/SourceFiles/platform/linux/linux_gtk_integration_p.h b/Telegram/SourceFiles/platform/linux/linux_gtk_integration_p.h
index 99d3579dd..9aab7e4fb 100644
--- a/Telegram/SourceFiles/platform/linux/linux_gtk_integration_p.h
+++ b/Telegram/SourceFiles/platform/linux/linux_gtk_integration_p.h
@@ -27,7 +27,9 @@ extern "C" {
 #endif // !LINK_TO_GTK
 
 // To be able to compile with gtk-2.0 headers as well
+#if !GTK_CHECK_VERSION(3, 0, 0)
 #define GdkMonitor GdkScreen
+#endif
 typedef struct _GtkAppChooser GtkAppChooser;
 
 namespace Platform {
```

**Comment by ilya-fedin** [comment]
And this
```
diff --git a/Telegram/SourceFiles/platform/linux/linux_gtk_integration_p.h b/Telegram/SourceFiles/platform/linux/linux_gtk_integration_p.h
index 99d3579dd..c12faa846 100644
--- a/Telegram/SourceFiles/platform/linux/linux_gtk_integration_p.h
+++ b/Telegram/SourceFiles/platform/linux/linux_gtk_integration_p.h
@@ -27,7 +27,7 @@ extern "C" {
 #endif // !LINK_TO_GTK
 
 // To be able to compile with gtk-2.0 headers as well
-#define GdkMonitor GdkScreen
+typedef struct _GdkMonitor GdkMonitor;
 typedef struct _GtkAppChooser GtkAppChooser;
 
 namespace Platform {
```

**Comment by noiseless** [comment]
> Please check if this fixes the issue

Applying this patch solves the problem. Great thanks!

**Comment by ilya-fedin** [comment]
The second patch is more preferable, please test it

**Comment by noiseless** [comment]
> The second patch is more preferable, please test it

With this patch, the build is also successful.

**Comment by ilya-fedin** [comment]
Thank you for testing

**Comment by noiseless** [comment]
Thank you for your quick response.

**Comment by reagentoo** [comment]
> The second patch is more preferable, please test it

It works. Thanks!
