### ISSUE TITLE
[Question] Compilation error (Windows, MSVC 2019) 

### ISSUE THREAD

**Issue by earshinov** [telegramdesktop/tdesktop#7950]
Hi!

I am trying to compile Telegram using this guide: https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md. I have generated the .sln file. but I get ~700 errors when I am trying to build the solution in Debug mode with Visual Studio.

The first error is 

```
Error	C2039	'result_of': is not a member of 'std' (compiling source file C:\tdesktop-build\tdesktop\Telegram\ThirdParty\libtgvoip\EchoCanceller.cpp)	lib_tgvoip	C:\tdesktop-build\tdesktop\Telegram\ThirdParty\libtgvoip\webrtc_dsp\absl\meta\type_traits.h	413	
```

Also, during build I get 3 message boxes like this:

```
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Assertion Failed!

Program: ...ktop\out\Telegram\codegen\codegen\lang\Debug\codegen_lang.exe
File: minkernel\crts\ucrt\src\appcrt\heap\debug_heap.cpp
Line: 904

Expression: _CrtIsValidHeapPointer(block)

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)

---------------------------
Abort   Retry   Ignore   
---------------------------
```

Can someone please give me some directions? Is there perhaps a different place to seek help with compilation? Building C++ project, especially a failrly large one like Telegram, is known to be a problematic process, so I am surprised not to see hundreds of similar questions here.

**Comment by john-preston** [comment]
@earshinov I didn't deploy fixes for build on msvc 16.6.0 yet. Although I didn't see that Debug Assertion Violation.

**Comment by earshinov** [comment]
Thanks for a prompt reply! I will wait then for build fixes.

**Comment by sapphire6666** [comment]
I get the same problem today, did you solve the problem?

**Comment by TeleFan777** [comment]
@john-preston What is the current version of msvc we can use for successful releases? Probably, it will be better to point it in the build instructions. Thanks.

**Comment by TeleFan777** [comment]
I also a bit confused due to this recommendation https://github.com/telegramdesktop/tdesktop/issues/7959. 
I expected to have vs & build tools of the same versions. 

@john-preston Can you just point us with versions of vs & build tools to have a successful result as I see that not only I have issues with building tg on the latests versions of vs & build tools.

**Comment by vaverkax** [comment]
@TeleFan777 I suppose you need to do following things:
1. Roll back vs to 16.5.0
2. checkout to 8d1db85 commit 
3. checkout all submodules to status that was at 8d1db85 commit

**Comment by TeleFan777** [comment]
@vaverkax thanks for quick reply!
just to clarify 16.5.0 should the version of VS or VS build tools?
P.S. sorry for noobs questions

**Comment by TeleFan777** [comment]
> checkout all submodules to status that was at 8d1db85 commit

@vaverkax can you, please, give me direction how can I align submodules with a specific commit in the repo? Thanks.

**Comment by vaverkax** [comment]
@TeleFan777 I think whole vs should be 16.5.0
its only an assumption  

I'll try it only on Monday 


> > checkout all submodules to status that was at [8d1db85](https://github.com/telegramdesktop/tdesktop/commit/8d1db85a2801c49e4b64e7daa1bb24d1533df9d9) commit
> 
> @vaverkax can you, please, give me direction how can I align submodules with a specific commit in the root(**tdesktop**) repo? Thanks.

its quite monotonous job

**Comment by TeleFan777** [comment]
> or maybe you can just pull whole root with its submodules from specific commit

@vaverkax **git submodule update** will align submodules heads to the root head. I will also try with your assumption, but I hope fixes will appear in the repo as soon as possible

**Comment by vaverkax** [comment]
After latest commit (793906c) I've got debug assertation errors on debug configuration:

![errors](https://user-images.githubusercontent.com/13656832/83517168-154a2900-a4e1-11ea-85d8-c6ecee976e17.png)
![debug_errors](https://user-images.githubusercontent.com/13656832/83517189-1b400a00-a4e1-11ea-8146-dbba89f1fe86.png)

And some errors in vs ~20.
Hope these screenshots will help to find reason because I can't find it

**Comment by kirsan31** [comment]
Exactly same problem here with debug build. V.S. 16.6.1.

**Comment by wxz879526** [comment]
![image](https://user-images.githubusercontent.com/7566672/84496685-f49f8180-acdf-11ea-9281-07e1c9042f96.png)

I also encountered the same problem, how to solve？

**Comment by john-preston** [comment]
@wxz879526 This is a regression in Visual Studio :(

You can try Visual Studio Preview 16.7.* (they say it is fixed there), or downgrade to Visual Studio 16.5.* (you'll need to update cmake_helpers submodule to the latest commit, where I've reverted workarounds for 16.6.*).

**Comment by fish6688** [comment]
Dear administrator. When I compile, I report the following error. I want to find a solution.

TBuild\tdesktop\Telegram\lib_ ui\ui/effects/cross_ Animation. H (9,1): fatal error C1083: could not open include file: 'styles / style_ widgets.h”: No such file or directory

>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): error MSB6006: “cmd.exe” Exited with code 1.

**Comment by megapro17** [comment]
![image](https://user-images.githubusercontent.com/16743370/87177305-1b070b80-c2e4-11ea-8fb7-94214374e8f4.png)
still no fix? Version 16.6.3

**Comment by ilya-fedin** [comment]
you need 16.7 preview or old 16.5 studio

**Comment by megapro17** [comment]
> you need 16.7 preview or old 16.5 studio

omg, when i'm installing preview studio it's also requires me installing gigabytes of sdk's and other tools... i guess i have to wait

**Comment by zhangqingfeng0105** [comment]
Using VS2019 16.5.0 can solve the above problems.
Its download link is https://docs.microsoft.com/en-us/visualstudio/releases/2019/history

**Comment by megapro17** [comment]
Why closed it? Downgrading is not a solution
