### ISSUE TITLE
1.2.1 build failure

### ISSUE THREAD

**Issue by xvitaly** [telegramdesktop/tdesktop#4173]
### Steps to reproduce
1. Build with TDESKTOP_DISABLE_CRASH_REPORTS flag.
2. 
3. 

### Expected behaviour
Successful build.

### Actual behaviour
Build failure:
```
[ 50%] Building CXX object CMakeFiles/Telegram.dir/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.o
/usr/bin/c++  -DNDEBUG -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_PLUGIN -DQT_WIDGETS_LIB -DQ_OS_LINUX64 -DTDESKTOP_DISABLE_AUTOUPDATE -DTDESKTOP_DISABLE_CRASH_REPORTS -DTDESKTOP_DISABLE_DESKTOP_FILE_GENERATION -DTDESKTOP_DISABLE_REGISTER_CUSTOM_SCHEME -DTDESKTOP_DISABLE_UNITY_INTEGRATION -DTGVOIP_USE_CXX11_LIB -D_REENTRANT -D__STDC_FORMAT_MACROS -I/builddir/build/BUILD/tdesktop-1.2.1/out/Release/../../Telegram/SourceFiles -I/builddir/build/BUILD/tdesktop-1.2.1/out/Release/obj/gen -I/builddir/build/BUILD/tdesktop-1.2.1/out/Release/../../Telegram/ThirdParty/emoji_suggestions -I/usr/include/qt5 -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore/5.9.2 -I/usr/include/qt5/QtGui/5.9.2 -I/usr/include/qt5/QtCore/5.9.2/QtCore -I/usr/include/qt5/QtGui/5.9.2/QtGui -I/usr/include/ffmpeg -I/usr/include/minizip -I/usr/include/opus -I/usr/include/libtgvoip -I/usr/include/guidelines-support-library -I/usr/include/range-v3 -I/usr/lib64/qt5/mkspecs/linux-g++  -O2 -g1 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic   -fPIC -Wno-unused-variable -Wno-unused-parameter -Wno-unused-function -Wno-switch -Wno-comment -Wno-unused-but-set-variable -Wno-missing-field-initializers -Wno-sign-compare -std=c++1z -Wno-register -Wno-strict-overflow -I/usr/include/libappindicator-0.1 -I/usr/include/libdbusmenu-glib-0.4 -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/atk-1.0 -pthread -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -pthread -I/usr/include/dee-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gio-unix-2.0/ -pthread -fno-strict-aliasing  "-include" "/builddir/build/BUILD/tdesktop-1.2.1/out/Release/Telegram_pch/stdafx.h" -o CMakeFiles/Telegram.dir/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.o -c /builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp: In destructor 'CrashReports::dump::~dump()':
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp:518:6: error: 'ReportFile' was not declared in this scope
  if (ReportFile) {
      ^~~~~~~~~~
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp:518:6: note: suggested alternative: 'AppFile'
  if (ReportFile) {
      ^~~~~~~~~~
      AppFile
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp: In function 'const CrashReports::dump& CrashReports::operator<<(const CrashReports::dump&, const char*)':
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp:524:7: error: 'ReportFile' was not declared in this scope
  if (!ReportFile) return stream;
       ^~~~~~~~~~
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp:524:7: note: suggested alternative: 'AppFile'
  if (!ReportFile) return stream;
       ^~~~~~~~~~
       AppFile
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp:526:30: error: 'ReportFile' was not declared in this scope
  fwrite(str, 1, strlen(str), ReportFile);
                              ^~~~~~~~~~
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp:526:30: note: suggested alternative: 'AppFile'
  fwrite(str, 1, strlen(str), ReportFile);
                              ^~~~~~~~~~
                              AppFile
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp: In function 'const CrashReports::dump& CrashReports::operator<<(const CrashReports::dump&, const wchar_t*)':
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp:531:10: error: 'ReportFile' was not declared in this scope
     if (!ReportFile) return stream;
          ^~~~~~~~~~
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp:531:10: note: suggested alternative: 'AppFile'
     if (!ReportFile) return stream;
          ^~~~~~~~~~
          AppFile
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp:535:4: error: 'SafeWriteChar' was not declared in this scope
    SafeWriteChar(char(str[i]));
    ^~~~~~~~~~~~~
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp:537:4: error: 'SafeWriteChar' was not declared in this scope
    SafeWriteChar('?');
    ^~~~~~~~~~~~~
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp: In function 'const CrashReports::dump& CrashReports::operator<<(const CrashReports::dump&, int)':
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp:544:9: error: 'SafeWriteNumber' was not declared in this scope
  return SafeWriteNumber(stream, num);
         ^~~~~~~~~~~~~~~
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp:544:9: note: suggested alternative: 'QVersionNumber'
  return SafeWriteNumber(stream, num);
         ^~~~~~~~~~~~~~~
         QVersionNumber
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp: In function 'const CrashReports::dump& CrashReports::operator<<(const CrashReports::dump&, unsigned int)':
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp:548:9: error: 'SafeWriteNumber' was not declared in this scope
  return SafeWriteNumber(stream, num);
         ^~~~~~~~~~~~~~~
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp:548:9: note: suggested alternative: 'QVersionNumber'
  return SafeWriteNumber(stream, num);
         ^~~~~~~~~~~~~~~
         QVersionNumber
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp: In function 'const CrashReports::dump& CrashReports::operator<<(const CrashReports::dump&, long unsigned int)':
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp:552:9: error: 'SafeWriteNumber' was not declared in this scope
  return SafeWriteNumber(stream, num);
         ^~~~~~~~~~~~~~~
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp:552:9: note: suggested alternative: 'QVersionNumber'
  return SafeWriteNumber(stream, num);
         ^~~~~~~~~~~~~~~
         QVersionNumber
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp: In function 'const CrashReports::dump& CrashReports::operator<<(const CrashReports::dump&, long long unsigned int)':
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp:556:9: error: 'SafeWriteNumber' was not declared in this scope
  return SafeWriteNumber(stream, num);
         ^~~~~~~~~~~~~~~
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp:556:9: note: suggested alternative: 'QVersionNumber'
  return SafeWriteNumber(stream, num);
         ^~~~~~~~~~~~~~~
         QVersionNumber
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp: In function 'const CrashReports::dump& CrashReports::operator<<(const CrashReports::dump&, double)':
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp:561:3: error: 'SafeWriteChar' was not declared in this scope
   SafeWriteChar('-');
   ^~~~~~~~~~~~~
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp:564:2: error: 'SafeWriteNumber' was not declared in this scope
  SafeWriteNumber(stream, uint64(floor(num)));
  ^~~~~~~~~~~~~~~
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp:564:2: note: suggested alternative: 'QVersionNumber'
  SafeWriteNumber(stream, uint64(floor(num)));
  ^~~~~~~~~~~~~~~
  QVersionNumber
/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.cpp:565:2: error: 'SafeWriteChar' was not declared in this scope
  SafeWriteChar('.');
  ^~~~~~~~~~~~~
make[2]: *** [CMakeFiles/Telegram.dir/build.make:2379: CMakeFiles/Telegram.dir/builddir/build/BUILD/tdesktop-1.2.1/Telegram/SourceFiles/core/crash_reports.o] Error 1
```

### Configuration
**Operating system:** Fedora 27

**Version of Telegram Desktop:** 1.2.1

**Used theme**: n/a

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by xvitaly** [comment]
Regression caused by 97c15865a5ae936ff0cd0fb2413a00f0d50fad45 commit.

**Comment by auchri** [comment]
@xvitaly Tests are also failing.

**Comment by john-preston** [comment]
@xvitaly Sorry :/

**Comment by xvitaly** [comment]
@john-preston Thanks for quick fix, but can you move `v1.2.1` tag to include this commit?
