### ISSUE TITLE
snap telegram not loading web app pop ups

### ISSUE THREAD

**Issue by jimi3** [telegramdesktop/tdesktop#27363]
### Steps to reproduce

ubuntu mate 22.04
telegram-desktop           4.14.3                      5390   latest/stable    telegram-desktop✓  -

1. Menu > Wallet
2. 
![image](https://github.com/telegramdesktop/tdesktop/assets/6639111/0cfb2622-f79e-42aa-a17a-2d5b784d6bc2)

### Expected behaviour

![image](https://github.com/telegramdesktop/tdesktop/assets/6639111/a214f874-1e12-46b6-aa3c-07e1d1d6515c)

### Actual behaviour

not loading pop up content

### Operating system

ubuntu mate 22.04

### Version of Telegram Desktop

snap stable 4.14.3 

### Installation source

Snap

### Logs

```shell
[2024.01.16 04:49:16] Launched version: 4014003, install beta: [FALSE], alpha: 0, debug mode: [FALSE]
[2024.01.16 04:49:16] Executable dir: /snap/telegram-desktop/5390/usr/bin/, name: telegram-desktop
[2024.01.16 04:49:16] Initial working dir: /home/user/
[2024.01.16 04:49:16] Working dir: /home/user/snap/telegram-desktop/5390/.local/share/TelegramDesktop/
[2024.01.16 04:49:16] Command line: /snap/telegram-desktop/5390/usr/bin/telegram-desktop --
[2024.01.16 04:49:16] Executable path before check: /snap/telegram-desktop/5390/usr/bin/telegram-desktop
[2024.01.16 04:49:16] Logs started
[2024.01.16 04:49:16] App ID: telegram-desktop_telegram-desktop
[2024.01.16 04:49:16] Connecting local socket to snap.telegram-desktop.67b8b88d45572385a43de79b63f7dd50...
[2024.01.16 04:49:16] Socket connect error 0, starting server and app...
[2024.01.16 04:49:16] Moved logging from '/home/user/snap/telegram-desktop/5390/.local/share/TelegramDesktop/log_start0.txt' to '/home/user/snap/telegram-desktop/5390/.local/share/TelegramDesktop/log.txt'!
[2024.01.16 04:49:16] Global devicePixelRatio: 1
[2024.01.16 04:49:16] QT_SCALE_FACTOR: 1
[2024.01.16 04:49:16] QT_FONT_DPI: 96
[2024.01.16 04:49:16] Primary screen DPI: 96, Base: 96.
[2024.01.16 04:49:16] Computed screen scale: 100
[2024.01.16 04:49:16] DevicePixelRatio: 1
[2024.01.16 04:49:16] ScreenScale: 100
[2024.01.16 04:49:16] Icon theme: Yaru-bark-dark
[2024.01.16 04:49:16] Fallback icon theme: 
[2024.01.16 04:49:16] System tray available: [TRUE]
[2024.01.16 04:49:16] Font: from ':/gui/fonts/DAOpenSansRegular.ttf' loaded 'DAOpenSansRegular'
[2024.01.16 04:49:16] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
[2024.01.16 04:49:16] Font: from ':/gui/fonts/DAOpenSansRegularItalic.ttf' loaded 'DAOpenSansRegularItalic'
[2024.01.16 04:49:16] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
[2024.01.16 04:49:16] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
[2024.01.16 04:49:16] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2024.01.16 04:49:16] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
[2024.01.16 04:49:16] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2024.01.16 04:49:16] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
[2024.01.16 04:49:16] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2024.01.16 04:49:16] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
[2024.01.16 04:49:16] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2024.01.16 04:49:16] App Info: reading settings...
[2024.01.16 04:49:16] App Info: reading encrypted settings...
[2024.01.16 04:49:16] Lang Info: Loaded cached, keys: 6091
[2024.01.16 04:49:16] OpenAL Logging Level: (not set)
[2024.01.16 04:49:16] Audio Playback Devices: Starship/Matisse HD Audio Controller Analog Stereo;Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590] Digital Stereo (HDMI 3)
[2024.01.16 04:49:16] Audio Playback Default Device: Starship/Matisse HD Audio Controller Analog Stereo
[2024.01.16 04:49:16] Audio Capture Devices: Monitor of Starship/Matisse HD Audio Controller Analog Stereo;Monitor of Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590] Digital Stereo (HDMI 3)
[2024.01.16 04:49:16] Audio Capture Default Device: Monitor of Starship/Matisse HD Audio Controller Analog Stereo
[2024.01.16 04:49:17] App Info: reading accounts info...
[2024.01.16 04:49:17] App Info: reading encrypted info...
[2024.01.16 04:49:17] App Info: reading map...
[2024.01.16 04:49:17] App Info: reading encrypted map...
[2024.01.16 04:49:17] App Info: reading encrypted user settings...
[2024.01.16 04:49:17] App Info: encrypted user settings read.
[2024.01.16 04:49:17] App Info: reading encrypted mtp data...
[2024.01.16 04:49:17] MTP Info: read keys, current: 4, to destroy: 0
[2024.01.16 04:49:17] Map read time: 1
[2024.01.16 04:49:17] App Info: reading encrypted mtp config...
[2024.01.16 04:49:17] Export Info: Destroy top bar by controller removal.
[2024.01.16 04:49:17] OpenGL Profile: Compatibility.
[2024.01.16 04:49:17] OpenGL Renderer: AMD Radeon RX 580 Series (radeonsi, polaris10, LLVM 15.0.7, DRM 3.49, 6.2.0-39-generic)
[2024.01.16 04:49:17] OpenGL Vendor: AMD
[2024.01.16 04:49:17] OpenGL Version: 4.6 (Compatibility Profile) Mesa 23.3.2 - kisak-mesa PPA
[2024.01.16 04:49:17] OpenGL Extensions: GL_ARB_program_interface_query, GL_EXT_texture_rectangle, GL_EXT_stencil_wrap, GL_NV_texture_barrier, GL_EXT_separate_specular_color, GL_ARB_draw_instanced, GL_AMD_multi_draw_indirect, GL_EXT_rescale_normal, GL_ARB_texture_barrier, GL_ARB_texture_rgb10_a2ui, GL_ARB_blend_func_extended, GL_ATI_texture_float, GL_ARB_texture_env_crossbar, GL_EXT_point_parameters, GL_IBM_rasterpos_clip, GL_ARB_multi_draw_indirect, GL_ATI_texture_env_combine3, GL_EXT_texture3D, GL_KHR_no_error, GL_EXT_blend_minmax, GL_ARB_conditional_render_inverted, GL_ARB_framebuffer_object, GL_ARB_texture_cube_map, GL_NV_primitive_restart, GL_ARB_texture_stencil8, GL_ARB_depth_clamp, GL_KHR_texture_compression_astc_sliced_3d, GL_EXT_blend_subtract, GL_INGR_blend_func_separate, GL_ARB_sync, GL_ARB_vertex_attrib_binding, GL_EXT_blend_func_separate, GL_EXT_gpu_shader4, GL_NV_half_float, GL_ARB_texture_query_lod, GL_AMD_shader_trinary_minmax, GL_EXT_abgr, GL_ARB_gpu_shader_fp64, GL_ARB_shading_language_include, GL_ARB_texture_gather, GL_ARB_vertex_array_bgra, GL_ARB_internalformat_query, GL_SGIS_texture_edge_clamp, GL_MESA_framebuffer_flip_y, GL_ARB_instanced_arrays, GL_ARB_direct_state_access, GL_AMD_texture_texture4, GL_ARB_texture_buffer_object, GL_MESA_window_pos, GL_EXT_subtexture, GL_AMD_conservative_depth, GL_ARB_fragment_layer_viewport, GL_ARB_gl_spirv, GL_ARB_shader_atomic_counter_ops, GL_EXT_texture_compression_rgtc, GL_EXT_texture_sRGB, GL_EXT_memory_object_fd, GL_EXT_window_rectangles, GL_ARB_color_buffer_float, GL_ARB_texture_rectangle, GL_ARB_texture_mirror_clamp_to_edge, GL_ARB_get_program_binary, GL_EXT_semaphore_fd, GL_ARB_query_buffer_object, GL_EXT_vertex_attrib_64bit, GL_ARB_enhanced_layouts, GL_ARB_robust_buffer_access_behavior, GL_ARB_texture_border_clamp, GL_KHR_robust_buffer_access_behavior, GL_ARB_shader_bit_encoding, GL_IBM_multimode_draw_arrays, GL_AMD_depth_clamp_separate, GL_ARB_half_float_pixel, GL_ARB_gpu_shader_int64, GL_ARB_shader_objects, GL_EXT_depth_bounds_test, GL_ANGLE_texture_compression_dxt5, GL_ARB_draw_elements_base_vertex, GL_EXT_polygon_offset_clamp, GL_EXT_texture_sRGB_decode, GL_ARB_shadow, GL_EXT_texture_shared_exponent, GL_ARB_shading_language_420pack, GL_ARB_transform_feedback_instanced, GL_KHR_robustness, GL_EXT_transform_feedback, GL_ARB_map_buffer_alignment, GL_EXT_framebuffer_sRGB, GL_ATI_fragment_shader, GL_EXT_debug_label, GL_AMD_vertex_shader_layer, GL_EXT_texture_compression_dxt1, GL_ATI_separate_stencil, GL_ARB_cull_distance, GL_ARB_tessellation_shader, GL_ATI_blend_equation_separate, GL_EXT_framebuffer_blit, GL_ARB_compatibility, GL_EXT_blend_color, GL_ARB_provoking_vertex, GL_EXT_draw_range_elements, GL_EXT_framebuffer_multisample, GL_ARB_texture_float, GL_EXT_packed_pixels, GL_ARB_texture_storage_multisample, GL_ARB_transform_feedback2, GL_ARB_spirv_extensions, GL_ARB_depth_buffer_float, GL_AMD_framebuffer_multisample_advanced, GL_EXT_texture_sRGB_R8, GL_ARB_ES3_1_compatibility, GL_ARB_fragment_program_shadow, GL_ATI_draw_buffers, GL_NVX_gpu_memory_info, GL_ARB_texture_buffer_range, GL_ARB_copy_image, GL_EXT_texture_integer, GL_EXT_vertex_array, GL_ARB_multitexture, GL_ARB_shader_texture_lod, GL_ARB_pixel_buffer_object, GL_ARB_viewport_array, GL_ARB_draw_indirect, GL_EXT_pixel_buffer_object, GL_ARB_shader_image_load_store, GL_SGIS_texture_border_clamp, GL_EXT_demote_to_helper_invocation, GL_AMD_vertex_shader_viewport_index, GL_EXT_texture_swizzle, GL_ARB_half_float_vertex, GL_MESA_texture_signed_rgba, GL_ARB_texture_filter_anisotropic, GL_EXT_fog_coord, GL_EXT_texture_mirror_clamp, GL_AMD_performance_monitor, GL_EXT_secondary_color, GL_SGIS_generate_mipmap, GL_ARB_depth_texture, GL_ARB_indirect_parameters, GL_NV_texture_env_combine4, GL_ARB_texture_buffer_object_rgb32, GL_ARB_occlusion_query, GL_ARB_shader_clock, GL_ARB_sampler_objects, GL_ARB_texture_rg, GL_EXT_packed_depth_stencil, GL_EXT_draw_instanced, GL_EXT_shader_image_load_formatted, GL_NV_blend_square, GL_EXT_shadow_funcs, GL_ARB_vertex_type_2_10_10_10_rev, GL_EXT_direct_state_access, GL_ARB_texture_swizzle, GL_MESA_shader_integer_functions, GL_ARB_shader_draw_parameters, GL_ARB_draw_buffers_blend, GL_NV_copy_depth_to_color, GL_ARB_window_pos, GL_ATI_meminfo, GL_MESA_texture_const_bandwidth, GL_ARB_bindless_texture, GL_EXT_texture_edge_clamp, GL_ARB_shader_ballot, GL_ATI_texture_mirror_once, GL_IBM_texture_mirrored_repeat, GL_NV_copy_image, GL_ARB_ES2_compatibility, GL_ARB_uniform_buffer_object, GL_EXT_texture_snorm, GL_ARB_base_instance, GL_EXT_shader_integer_mix, GL_EXT_stencil_two_side, GL_ARB_compressed_texture_pixel_storage, GL_ARB_map_buffer_range, GL_ARB_draw_buffers, GL_ARB_point_sprite, GL_ARB_separate_shader_objects, GL_ARB_shader_viewport_layer_array, GL_ARB_texture_compression_rgtc, GL_ARB_fragment_program, GL_ATI_texture_compression_3dc, GL_EXT_texture_compression_s3tc, GL_EXT_bgra, GL_ARB_framebuffer_no_attachments, GL_ARB_stencil_texturing, GL_SGIS_texture_lod, GL_NV_packed_depth_stencil, GL_ARB_texture_non_power_of_two, GL_ARB_texture_query_levels, GL_ARB_internalformat_query2, GL_EXT_EGL_sync, GL_EXT_packed_float, GL_ARB_explicit_attrib_location, GL_ARB_texture_view, GL_EXT_gpu_program_parameters, GL_EXT_vertex_array_bgra, GL_EXT_copy_texture, GL_ARB_gpu_shader5, GL_ARB_vertex_attrib_64bit, GL_EXT_memory_object, GL_ARB_clear_texture, GL_ARB_vertex_buffer_object, GL_ARB_multisample, GL_NV_alpha_to_coverage_dither_control, GL_AMD_query_buffer_object, GL_ARB_invalidate_subdata, GL_ARB_transform_feedback3, GL_AMD_pinned_memory, GL_ARB_fragment_shader, GL_ARB_buffer_storage, GL_ARB_robustness, GL_S3_s3tc, GL_APPLE_packed_pixels, GL_ARB_shading_language_packing, GL_AMD_seamless_cubemap_per_texture, GL_EXT_draw_buffers2, GL_ARB_shader_atomic_counters, GL_NV_conditional_render, GL_ARB_vertex_type_10f_11f_11f_rev, GL_ARB_shader_subroutine, GL_ARB_pipeline_statistics_query, GL_ARB_get_texture_sub_image, GL_ARB_vertex_program, GL_EXT_framebuffer_multisample_blit_scaled, GL_ARB_transpose_matrix, GL_ARB_ES3_2_compatibility, GL_OES_EGL_image, GL_ANGLE_texture_compression_dxt3, GL_ARB_arrays_of_arrays, GL_ARB_framebuffer_sRGB, GL_ARB_point_parameters, GL_EXT_compiled_vertex_array, GL_KHR_parallel_shader_compile, GL_EXT_texture_cube_map, GL_ARB_compute_shader, GL_NV_texgen_reflection, GL_ARB_timer_query, GL_ARB_texture_compression_bptc, GL_EXT_timer_query, GL_EXT_shader_samples_identical, GL_ARB_texture_multisample, GL_MESA_pack_invert, GL_ARB_multi_bind, GL_ARB_vertex_shader, GL_ARB_texture_storage, GL_EXT_provoking_vertex, GL_EXT_texture_object, GL_SUN_multi_draw_arrays, GL_INTEL_blackhole_render, GL_EXT_texture_env_add, GL_KHR_blend_equation_advanced, GL_ARB_polygon_offset_clamp, GL_ARB_texture_compression, GL_ARB_texture_env_add, GL_ARB_debug_output, GL_ARB_shader_group_vote, GL_ARB_transform_feedback_overflow_query, GL_NV_vdpau_interop, GL_KHR_debug, GL_ARB_conservative_depth, GL_ARB_shader_image_size, GL_ARB_texture_env_dot3, GL_ARB_vertex_array_object, GL_ARB_parallel_shader_compile, GL_EXT_texture_env_dot3, GL_ARB_copy_buffer, GL_ARB_compute_variable_group_size, GL_ARB_ES3_compatibility, GL_OES_read_format, GL_AMD_shader_stencil_export, GL_ARB_derivative_control, GL_NV_texture_rectangle, GL_EXT_texture_buffer_object, GL_NV_ES1_1_compatibility, GL_ARB_clip_control, GL_EXT_texture_array, GL_ARB_seamless_cube_map, GL_EXT_texture_lod_bias, GL_EXT_EGL_image_storage, GL_EXT_framebuffer_object, GL_ARB_seamless_cubemap_per_texture, GL_NV_compute_shader_derivatives, GL_ARB_texture_mirrored_repeat, GL_AMD_draw_buffers_blend, GL_ARB_explicit_uniform_location, GL_EXT_texture_filter_anisotropic, GL_KHR_context_flush_control, GL_ARB_texture_cube_map_array, GL_EXT_multi_draw_arrays, GL_EXT_semaphore, GL_ARB_fragment_coord_conventions, GL_EXT_texture_shadow_lod, GL_ARB_shader_texture_image_samples, GL_NV_shader_atomic_int64, GL_KHR_texture_compression_astc_ldr, GL_EXT_shader_image_load_store, GL_ARB_shader_precision, GL_NV_light_max_exponent, GL_EXT_blend_equation_separate, GL_EXT_texture_env_combine, GL_ARB_sample_shading, GL_EXT_texture, GL_NV_fog_distance, GL_ARB_texture_env_combine, GL_EXT_texture_compression_latc, GL_ARB_shader_stencil_export, GL_ARB_clear_buffer_object, GL_ARB_occlusion_query2, GL_ARB_shader_storage_buffer_object, GL_NV_depth_clamp, GL_ARB_shading_language_100
[2024.01.16 04:49:17] OpenGL: QOpenGLContext created, version: 4.4.
[2024.01.16 04:49:17] OpenGL: [TRUE] (Window)
[2024.01.16 04:49:19] API Warning: not loaded minimal channel applied.
[2024.01.16 04:49:19] RPC Error: request 119 got fail with code 400, error WEBFILE_NOT_AVAILABLE
[2024.01.16 04:49:20] Message Info: bad message notification received (error_code 33) for msg_id = 7324522806340720116, seq_no = 364
[2024.01.16 04:49:20] Message Info: bad message notification received, msgId 7324522806340720116, error_code 33
[2024.01.16 04:49:21] API Warning: not loaded minimal channel applied.
[2024.01.16 04:49:21] RPC Error: request 245 got fail with code 400, error WEBFILE_NOT_AVAILABLE
[2024.01.16 04:49:26] RPC Error: request 264 got fail with code 400, error USER_NOT_PARTICIPANT
[2024.01.16 04:54:54] API Warning: not loaded minimal channel applied.
[2024.01.16 04:56:11] API Warning: not loaded minimal channel applied.
[2024.01.16 05:02:20] Skipping message, because it is already in blocks!
[2024.01.16 05:02:23] Skipping message, because it is already in blocks!
```

**Comment by ilya-fedin** [comment]
Perhaps your application is using too new web apis? Linux has webkit that is lacking modern web apis.

**Comment by jimi3** [comment]
Would have to tell me how to look where for further debug details, this has been bugging me now for Months on a default ubuntu 22.04 install with 24.04 on the Horizon. 
Run into this same problem when i tested 23.10 and 24.04.
Forgot to mention that it works in,
` chromium                   120.0.6099.216              2729   latest/stable    canonical✓.`

Also had tested latest/edge, same problem.
Not sure what options remain for the snap desktop version.

**Comment by ilya-fedin** [comment]
Enable web view debugging in experimental settings?

**Comment by jimi3** [comment]
with the snap tg update (4.14.6-7-gc364383cf)  i can see a crash error.
![image](https://github.com/telegramdesktop/tdesktop/assets/6639111/95cd3731-2e0d-436e-aa8e-dacce8276e12)
webview inspection does not allow me to right click in web app, there is no right click

**Comment by ilya-fedin** [comment]
Well, it means your application causes a crash of the Linux system web engine (webkitgtk). I don't think anything could be done in tdesktop to fix this.

**Comment by ilya-fedin** [comment]
It's fully functional, just your code crashes system component.

**Comment by jimi3** [comment]
How can it be fully functional on a current major default Linux system?
Maybe i get this wrong but i tried to pick a web app (Wallet) that is afaik produced by tg themselves.
It is in the main Menu after all.
Could use some more details here.

**Comment by ilya-fedin** [comment]
Ah, apparently I've read the issue wrongly. I thought the problem is with your own web app.

**Comment by CreaturePH** [comment]
This is not a specific web app issue, webview does not work for any web app. Didn't work in Ubuntu 20.04 and doesn't work now after updating to Ubuntu 22.04. At the moment, Telegram Version 4.14.15 is installed, from the Snap Store. Could it be that my system is missing some component? What exactly does Telegram use to display web content?

**Comment by ilya-fedin** [comment]
> Could it be that my system is missing some component?

No, it's just broken in both flatpak and snap. The exact reason why it's broken is unknown (or it would be fixed long time ago) but the allocator seem to say there's a misaligned pointer what may mean webkit corrupts memory.

> What exactly does Telegram use to display web content?

webkitgtk

**Comment by b1ek** [comment]
same issue here on arch, tdesktop 4.15

**Comment by NgoHuy** [comment]
I got this issue today, the message from log here:
```
(telegram-desktop:29574): GLib-GIO-WARNING **: 08:58:53.925: Your application does not implement g_application_activate() and has no handlers connected to the 'activate' signal.  It should do one of these.
qt.waylandcompositor.hardwareintegration: Failed to initialize EGL display. Could not get EglDisplay for window.

(telegram-desktop:29583): GLib-GIO-WARNING **: 08:58:54.040: Your application does not implement g_application_activate() and has no handlers connected to the 'activate' signal.  It should do one of these.
Cannot get default EGL display: EGL_BAD_PARAMETER

** (telegram-desktop:29583): WARNING **: 08:58:54.174: Disabled hardware acceleration because GTK failed to initialize GL: GL support disabled via GDK_DEBUG.
error in client communication (pid 29583)
Gdk-Message: 08:58:54.276: Error 71 (Protocol error) dispatching to Wayland display.
```
I have found workaround: `GDK_BACKEND=x11 telegram-desktop`, it forces use GDK_BACKEND with X11, it seems to gdk is called from X11 only, not wayland compatible.

**Comment by ilya-fedin** [comment]
hmm, qt in snap is patched to not to return protocol error, are you sure you're writing in the right issue?

**Comment by NgoHuy** [comment]
Sorry, I use archlinux with qt system. It showed same error: webview crashed.

**Comment by ilya-fedin** [comment]
@NgoHuy you can get the version from official website and it should just work. For system Qt, you have to ask its maintainers to apply tdesktop's Qt patchset.

**Comment by NgoHuy** [comment]
> @NgoHuy you can get the version from official website and it should just work. For system Qt, you have to ask its maintainers to apply tdesktop's Qt patchset.

Thank you very much. But I cannot find the patchset. Could you give me the link?

**Comment by ilya-fedin** [comment]
https://github.com/desktop-app/patches

**Comment by ilya-fedin** [comment]
The https://github.com/desktop-app/patches/blob/master/qtwayland_6.6.2/0004-fix-gtk4-embedding.patch specifically

**Comment by php4fan** [comment]
Is there any workaround?

**Comment by ilya-fedin** [comment]
Don't use snap or flatpak versions. Don't know any other.

**Comment by vizzah** [comment]
I have the same issue with the latest 'telegram-desktop 4.15.0-1' under Manjaro/Arch on KDE5 under Wayland.

Webapps are not crashing in Telegram downloaded from Telegram.org:
executable 'Telegram', version 14.5.2, size 168,176,936

distro executable is 95,187,864 - significantly smaller and must be relying on external libs and the crash happens in-between.

**Comment by php4fan** [comment]
Funny thing is the flatpak version also uses the system's webkit-gtk-or-whatever library (which kind of defeats the purpose of flatpak doesn't it). It asked me to install it when I was running the flatpak version.

Maybe if the flatpak included the version it needs in the normal "flatpak way" that would solve the issue?

**Comment by ilya-fedin** [comment]
No, the flatpak package has webview in another flatpak package called "org.telegram.desktop.webview". Flatpak packages can't use host libraries, because they have no access to them and even if you would give, you would have to mess with environment variables to specifiy paths to them, an even after that you're likely to not to get them to work due to the difference in glibc version between the flatpak runtime and your host (or even another libc completely on the host).

**Comment by php4fan** [comment]
> No, the flatpak package has webkitgtk library in another flatpak package

Well, when I first tried to open a webapp in telegram desktop flatpak version, it would show an error message saying it couldn't open the webview because some library was missing, and it **explicitly told me do install a system package called webkit-sdk-something** or something similar. I retrieved several times and it would consistently fail with the same report.

So I installed that package on the host system (not flatpak). I was very skeptical that it was going to work because of the same reasons you mention, but after that, it stopped showing the error about the missing library and it started opening the webview that crashes instead.

**Comment by ilya-fedin** [comment]
That means there's a coincidence

**Comment by vizzah** [comment]
> That means there's a coincidence

Exactly the same happened to me. Installed 'telegram-desktop' package on Arch, when accessing webapp functions in Telegram it requested to install webkitgtk-6.0.
After it was installed, Telegram started crashing in webview.

Non-distro Telegram works fine, as already mentioned.

**Comment by ilya-fedin** [comment]
> Exactly the same happened to me.

The talk is about flatpak. So it's not the same as yours. Distro packages won't work as upstream Qt kills gtk4 Wayland clients when embedding their windows, static binary/flatpak/snap have patched Qt for that to work.

**Comment by ilya-fedin** [comment]
Is this still a problem (please don't answer if you're using a distro package, it's unrelated, to this issue)?

**Comment by jimi3** [comment]
i switched to flatpak a month ago so not sure if it works for the snap package but noticed few hours ago that most now are showing up and are working. There was an update on flatpak yesterday.
![image](https://github.com/telegramdesktop/tdesktop/assets/6639111/3d9082c8-4714-497a-ad0d-554742ea6d18)

So far i have found only one not yet working, if you want to check it out it's the [XBlast app](https://t.me/XBlastAppBot/App?startapp=MDVDSL)

**Comment by ilya-fedin** [comment]
So the issue could be closed?

**Comment by webportnoy** [comment]
Latest version 4.16..8 downloaded from telegram.org
Kubuntu 22.04
KDE 5.24.7
Qt: 5.15.3
X11

Webview still not work. What i need to do to make it works?

**Comment by EndorFlem** [comment]
Same issue

**Comment by webportnoy** [comment]
When starting any mini app (webview) getting this error:

```
(Telegram:7765): GLib-GIO-WARNING **: 09:05:51.372: Your application does not implement g_application_activate() and has no handlers connected to the 'activate' signal.  It should do one of these.
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 384x590: Permission denied
```

downloaded from telegram.org
Kubuntu 22.04
KDE 5.24.7
Qt: 5.15.3
X11

**Comment by Lippiece** [comment]
I am also getting the same error. May I suggest reopening the issue?

Operating System: Garuda Linux 
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.0
Kernel Version: 6.9.0-1-mainline (64-bit)
Graphics Platform: Wayland

> When starting any mini app (webview) getting this error:
> 
> ```
> (Telegram:7765): GLib-GIO-WARNING **: 09:05:51.372: Your application does not implement g_application_activate() and has no handlers connected to the 'activate' signal.  It should do one of these.
> KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
> Failed to create GBM buffer of size 384x590: Permission denied
> ```
> 
> downloaded from telegram.org Kubuntu 22.04 KDE 5.24.7 Qt: 5.15.3 X11

**Comment by php4fan** [comment]
After KDE got upgraded to version 6 and switched to Wayland (as opposed to X11), I now get this error when I try to open a webapp in Telegram Desktop (official static binary):

![image](https://github.com/telegramdesktop/tdesktop/assets/13969584/d7a17b01-6fa4-4859-93c1-3096760527dd)

despite the fact that I do have `webkitgtk-6.0` installed.
It used to work on KDE 5 / X11.

**Comment by php4fan** [comment]
I updated Telegram to 5.0.2 (from 4.something), didn't fix it, then I restarted Telegram (again) and now it's working.

**Comment by ilya-fedin** [comment]
Folks, this is an issue about web applications in snap version not working at all. I checked snap version and I see it works just fine, so I see no reason for reopening, the issue is not here.

**Comment by webportnoy** [comment]
> Folks, this is an issue about web applications in snap version not working at all. I checked snap version and I see it works just fine, so I see no reason for reopening, the issue is not here.

Can you publish instructions, what exactly we need to do before close issue? It could be good to see some message about this trouble in Telegram app when opening miniapp. Now users see black screen instead of miniapp, and don't know why is it so and what to do. It's not good, don't you think so?

**Comment by ilya-fedin** [comment]
> It's not good, don't you think so?

If you have a problem, it's not a reason to mess with an unrelated issue.

**Comment by webportnoy** [comment]
> If you have a problem, it's not a reason to mess with an unrelated issue.
Is it official Telegram position? Sounds very strange. Miniapps is one of main features in Telegram. Telegram could give some instructions, at least. Is it so difficult?

**Comment by ilya-fedin** [comment]
> Telegram could give some instructions, at least. Is it so difficult?

I don't know which instructions you're talking about.

**Comment by ilya-fedin** [comment]
What I want to say is, create new reports for new problems. Don't mess with old solved issues.

**Comment by webportnoy** [comment]
> I don't know which instructions you're talking about.

Instructions about what we need to do, to make miniapps work on Linux? 

I have kubutu, Telegram Desktop downloaded from telegram.org (not snap). 
I tried to install firefox (not snap) from official site mozilla.org and made it browser by default. 
But miniapps still can't work, black screen. So it looks like it's not snap problem.

**Comment by ilya-fedin** [comment]
> So it looks like it's not snap problem.

That is. If you're using not a snap, you don't have the issue discussed here, you have some other issue. Please stop off-topic.
