### ISSUE TITLE
Wallet WebApp bot not working on GNOME 45.2

### ISSUE THREAD

**Issue by kaiyga** [telegramdesktop/tdesktop#27251]
### Steps to reproduce

Install Wayland, Gnome shell
pacman -S telegram-desktop

1.Start Telegram-Desktop. Open wallet
2.Waiting...Waiting...Waiting!?!

### Expected behaviour

View menu of Wallet like at on my phone? 

### Actual behaviour

Infinity loading

![Screenshot from 2023-12-19 05-06-07](https://github.com/telegramdesktop/tdesktop/assets/92279086/a678d495-67c6-48fa-943d-5726bcd20900)

https://github.com/telegramdesktop/tdesktop/assets/92279086/df190428-44de-4a03-a7b1-d75f707ddf5c

### Operating system

Arch Linux | Wayland | Shell Gnome 45.2 

### Version of Telegram Desktop

4.12.2

### Installation source

Other (unofficial) source

### Logs

```shell
qt.svg: Error while inflating gzip file: SVG format check failed
unable to lock lockfile /run/user/1000/wayland-0.lock, maybe another compositor is running

(telegram-desktop:62942): GLib-GIO-WARNING **: 18:51:14.598: Your application does not implement g_application_activate() and has no handlers connected to the 'activate' signal.  It should do one of these.

(telegram-desktop:62942): Gtk-WARNING **: 18:51:14.767: Theme parser error: gtk.css:7791:21-28: Expected a valid color.

(telegram-desktop:62942): Gtk-WARNING **: 18:51:14.767: Theme parser error: gtk.css:7796:21-28: Expected a valid color.

(telegram-desktop:62942): Gtk-WARNING **: 18:51:14.767: Theme parser error: gtk.css:7814:21-28: Expected a valid color.

(telegram-desktop:62942): Gtk-WARNING **: 18:51:14.767: Theme parser error: gtk.css:7820:21-28: Expected a valid color.

(telegram-desktop:62942): Gtk-WARNING **: 18:51:14.801: Theme parser error: gtk.css:7791:21-28: Expected a valid color.

(telegram-desktop:62942): Gtk-WARNING **: 18:51:14.801: Theme parser error: gtk.css:7796:21-28: Expected a valid color.

(telegram-desktop:62942): Gtk-WARNING **: 18:51:14.801: Theme parser error: gtk.css:7814:21-28: Expected a valid color.

(telegram-desktop:62942): Gtk-WARNING **: 18:51:14.801: Theme parser error: gtk.css:7820:21-28: Expected a valid color.
error in client communication (pid 62942)
Gdk-Message: 18:51:14.927: Error 71 (Protocol error) dispatching to Wayland display.
```

**Comment by ilya-fedin** [comment]
Yeah, it looks like webkigtk has lost compatibility with QtWaylandCompositor in one of recent updates so apparently it won't work on Wayland anymore (in case of GNOME on X11 as well).

**Comment by kaiyga** [comment]
This is not a solution to the problem, but only a statement. But that's good too
Thanks

**Comment by ilya-fedin** [comment]
Yeah, there's sadly no solution. Maybe web bots should be disabled on Linux...

**Comment by ilya-fedin** [comment]
@Aokromes i guess it's not really a 3rd party, tdesktop has to acknowledge this by disabling or removing the non-working implementation. Maybe also add this to #25126 so someone would help to report this to Qt or webkitgtk...

**Comment by ilya-fedin** [comment]
Ideally [the cross-platform API abstraction](https://github.com/desktop-app/lib_webview/blob/3495eb8dd8f4e2dab9493b4a698e5006fadbca47/webview/webview_embed.h#L32) should get API to signal that the webview has crashed so the window could display a text for that instead of just being empty. Once the API is made, it should be connected to the platform code [here](https://github.com/desktop-app/lib_webview/blob/3495eb8dd8f4e2dab9493b4a698e5006fadbca47/webview/platform/linux/webview_linux_webkitgtk.cpp#L808). After that the API users ([1](https://github.com/telegramdesktop/tdesktop/blob/3adbfb1fb50695702c041cb3384582b64091e803/Telegram/SourceFiles/payments/ui/payments_panel.cpp#L527), [2](https://github.com/telegramdesktop/tdesktop/blob/3adbfb1fb50695702c041cb3384582b64091e803/Telegram/SourceFiles/ui/chat/attach/attach_bot_webview.cpp#L558)) just have to listen to the signal and display the text.

By signal I mean not a Qt signal (they're discouraged in tdesktop codebase) but a rpl::producer or a function to set a handler like already existing ones in the class. Sadly I haven't got anywhere in discusstions with @john-preston about the API, apparently he is too busy...

**Comment by ilya-fedin** [comment]
I tried to craft something based on the pre-existing widget destruction signal, it won't work with X11 but will with Wayland where most crashes seem to happen
