### PR TITLE
Fix build with clang 19.1.0.

### LINKED ISSUE #28283: Fails to build with Clang 19
### Steps to reproduce

1. Install a current build of clang 19.x
2. Try to build tdesktop with it

### Expected behaviour

It compiles

### Actual behaviour

Build fails because of recent changes to the template syntax (CWG 96).
See
https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#96
https://github.com/llvm/llvm-project/pull/80801

### Operating system

OpenMandriva Cooker

### Version of Telegram Desktop

5.4.1

### Installation source

Other (unofficial) source

### Crash ID

_No response_

### Logs

```shell
In file included from /home/bero/failed-builds/telegram-desktop/BUILD/telegram-desktop-5.4.1-build/tdesktop-5.4.1-full/build/Telegram/gen/lang_auto.cpp:10:
In file included from /home/bero/failed-builds/telegram-desktop/BUILD/telegram-desktop-5.4.1-build/tdesktop-5.4.1-full/build/Telegram/gen/lang_auto.h:13:
/home/bero/failed-builds/telegram-desktop/BUILD/telegram-desktop-5.4.1-build/tdesktop-5.4.1-full/Telegram/SourceFiles/lang/lang_values.h:72:43: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
   72 |                 return ReplaceUnwrap<Tags...>::template Call(
      |                                                         ^
/home/bero/failed-builds/telegram-desktop/BUILD/telegram-desktop-5.4.1-build/tdesktop-5.4.1-full/Telegram/SourceFiles/lang/lang_values.h:95:43: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
   95 |                 return ReplaceUnwrap<Tags...>::template Call(
      |                                                         ^
/home/bero/failed-builds/telegram-desktop/BUILD/telegram-desktop-5.4.1-build/tdesktop-5.4.1-full/Telegram/SourceFiles/lang/lang_values.h:164:43: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  164 |                 return ReplaceUnwrap<Tags...>::template Call(
      |                                                         ^
In file included from /home/bero/failed-builds/telegram-desktop/BUILD/telegram-desktop-5.4.1-build/tdesktop-5.4.1-full/build/Telegram/gen/lang_auto.cpp:10:
/home/bero/failed-builds/telegram-desktop/BUILD/telegram-desktop-5.4.1-build/tdesktop-5.4.1-full/build/Telegram/gen/lang_auto.h:360:48: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  360 |                 return ::Lang::details::Producer<>::template Combine(base, std::move(p));
      |                                                              ^
/home/bero/failed-builds/telegram-desktop/BUILD/telegram-desktop-5.4.1-build/tdesktop-5.4.1-full/build/Telegram/gen/lang_auto.h:365:48: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  365 |                 return ::Lang::details::Producer<>::template Current(base, std::move(p));
      |                                                              ^
/home/bero/failed-builds/telegram-desktop/BUILD/telegram-desktop-5.4.1-build/tdesktop-5.4.1-full/build/Telegram/gen/lang_auto.h:375:72: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  375 |                 return ::Lang::details::Producer<lngtag_month, lngtag_day>::template Combine(base, std::move(p), month__val, day__val);
      |                                                                                      ^
/home/bero/failed-builds/telegram-desktop/BUILD/telegram-desktop-5.4.1-build/tdesktop-5.4.1-full/build/Telegram/gen/lang_auto.h:380:72: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  380 |                 return ::Lang::details::Producer<lngtag_month, lngtag_day>::template Current(base, std::move(p), month__val, day__val);
      |                                                                                      ^
/home/bero/failed-builds/telegram-desktop/BUILD/telegram-desktop-5.4.1-build/tdesktop-5.4.1-full/build/Telegram/gen/lang_auto.h:390:85: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  390 |                 return ::Lang::details::Producer<lngtag_month, lngtag_day, lngtag_year>::template Combine(base, std::move(p), month__val, day__val, year__val);
      |                                                                                                   ^
/home/bero/failed-builds/telegram-desktop/BUILD/telegram-desktop-5.4.1-build/tdesktop-5.4.1-full/build/Telegram/gen/lang_auto.h:395:85: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  395 |                 return ::Lang::details::Producer<lngtag_month, lngtag_day, lngtag_year>::template Current(base, std::move(p), month__val, day__val, year__val);
      |                                                                                                   ^
/home/bero/failed-builds/telegram-desktop/BUILD/telegram-desktop-5.4.1-build/tdesktop-5.4.1-full/build/Telegram/gen/lang_auto.h:405:73: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  405 |                 return ::Lang::details::Producer<lngtag_month, lngtag_year>::template Combine(base, std::move(p), month__val, year__val);
      |                                                                                       ^
/home/bero/failed-builds/telegram-desktop/BUILD/telegram-desktop-5.4.1-build/tdesktop-5.4.1-full/build/Telegram/gen/lang_auto.h:410:73: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  410 |                 return ::Lang::details::Producer<lngtag_month, lngtag_year>::template Current(base, std::move(p), month__val, year__val);
      |                                                                                       ^
/home/bero/failed-builds/telegram-desktop/BUILD/telegram-desktop-5.4.1-build/tdesktop-5.4.1-full/build/Telegram/gen/lang_auto.h:420:60: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  420 |                 return ::Lang::details::Producer<lngtag_count>::template Combine(base, std::move(p), type, count__val);
      |                                                                          ^
/home/bero/failed-builds/telegram-desktop/BUILD/telegram-desktop-5.4.1-build/tdesktop-5.4.1-full/build/Telegram/gen/lang_auto.h:425:60: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  425 |                 return ::Lang::details::Producer<lngtag_count>::template Current(base, std::move(p), type, count__val);
      |                                                                          ^
/home/bero/failed-builds/telegram-desktop/BUILD/telegram-desktop-5.4.1-build/tdesktop-5.4.1-full/build/Telegram/gen/lang_auto.h:435:59: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  435 |                 return ::Lang::details::Producer<lngtag_time>::template Combine(base, std::move(p), time__val);
      |                                                                         ^
/home/bero/failed-builds/telegram-desktop/BUILD/telegram-desktop-5.4.1-build/tdesktop-5.4.1-full/build/Telegram/gen/lang_auto.h:440:59: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  440 |                 return ::Lang::details::Producer<lngtag_time>::template Current(base, std::move(p), time__val);
      |                                                                         ^
/home/bero/failed-builds/telegram-desktop/BUILD/telegram-desktop-5.4.1-build/tdesktop-5.4.1-full/build/Telegram/gen/lang_auto.h:450:59: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  450 |                 return ::Lang::details::Producer<lngtag_date>::template Combine(base, std::move(p), date__val);
      |                                                                         ^
/home/bero/failed-builds/telegram-desktop/BUILD/telegram-desktop-5.4.1-build/tdesktop-5.4.1-full/build/Telegram/gen/lang_auto.h:455:59: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  455 |                 return ::Lang::details::Producer<lngtag_date>::template Current(base, std::move(p), date__val);
      |                                                                         ^
/home/bero/failed-builds/telegram-desktop/BUILD/telegram-desktop-5.4.1-build/tdesktop-5.4.1-full/build/Telegram/gen/lang_auto.h:465:72: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  465 |                 return ::Lang::details::Producer<lngtag_date, lngtag_time>::template Combine(base, std::move(p), date__val, time__val);
      |                                                                                      ^
/home/bero/failed-builds/telegram-desktop/BUILD/telegram-desktop-5.4.1-build/tdesktop-5.4.1-full/build/Telegram/gen/lang_auto.h:470:72: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  470 |                 return ::Lang::details::Producer<lngtag_date, lngtag_time>::template Current(base, std::move(p), date__val, time__val);
      |                                                                                      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```
```

### PR DESCRIPTION
**Pull request by VladislavGrudinin**
Fixes #28283.

For more info see https://github.com/llvm/llvm-project/pull/80801.

Also can be fixed by using -Wno-missing-template-arg-list-after-template-kw
https://clang.llvm.org/docs/DiagnosticsReference.html#wmissing-template-arg-list-after-template-kw

### CODE REVIEW

**Comment by john-preston** [comment]
Please update codegen submodule to the commit that appeared in it's upstream repository so that I could merge it together with those changes.
