### ISSUE TITLE
3.5.0 release fails to build

### ISSUE THREAD

**Issue by klemensn** [telegramdesktop/tdesktop#23994]
### Steps to reproduce

Build https://github.com/telegramdesktop/tdesktop/releases/download/v3.5.0/tdesktop-3.5.0-full.tar.gz

### Expected behaviour

Compile without errors.

### Actual behaviour

The bundled `tgcalls` fails due to a missing include.

### Operating system

OpenBSD/amd64 7.0 -CURRENT

### Version of Telegram Desktop

3.5.0

### Installation source

Other (unofficial) source

### Logs

```shell
FAILED: Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/group/GroupInstanceCustomImpl.cpp.o                                                                                                                        
/usr/ports/pobj/tdesktop-3.5.0/bin/c++ -DBWE_TEST_LOGGING_COMPILE_TIME_ENABLE=0 -DDESKTOP_APP_DISABLE_CRASH_REPORTS -DDESKTOP_APP_DISABLE_DBUS_INTEGRATION -DDESKTOP_APP_DISABLE_WAYLAND_INTEGRATION -DDESKTOP_APP_USE_PACKAGED -D
HAVE_WEBRTC_VIDEO -DNO_MAIN_THREAD_WRAPPING -DQT_IMPLICIT_QCHAR_CONSTRUCTION -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_KEYWORDS -DRTC_DISABLE_TRACE_EVENTS -DRTC_ENABLE_VP9 -DTGCALLS_USE_STD_OPTIONAL -DWEBRTC_APM_DEBUG_DUMP=0 -DWEBRT
C_APP_TDESKTOP -DWEBRTC_DUMMY_AUDIO_BUILD -DWEBRTC_ENABLE_PROTOBUF=0 -DWEBRTC_HAVE_USRSCTP -DWEBRTC_INCLUDE_INTERNAL_AUDIO_DEVICE -DWEBRTC_LIBRARY_IMPL -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=1 -DWEBRTC_OPENBSD -DWEBRTC_OPUS_
SUPPORT_120MS_PTIME=1 -DWEBRTC_OPUS_VARIABLE_COMPLEXITY=0 -DWEBRTC_POSIX -DWEBRTC_USE_BUILTIN_ISAC_FLOAT -DWEBRTC_USE_H264 -DWEBRTC_USE_X11 -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -I/usr/ports/pobj/tdesktop-3.5.0/tdesktop-3.
5.0-full/Telegram/ThirdParty/tgcalls -I/usr/ports/pobj/tdesktop-3.5.0/tdesktop-3.5.0-full/Telegram/ThirdParty/tgcalls/tgcalls -isystem /usr/local/include/tg_owt -isystem /usr/local/include -isystem /usr/local/include/tg_owt/th
ird_party/libyuv/include -O2 -pipe  -DCRL_FORCE_QT -DNDEBUG -Wno-deprecated-volatile -Wno-ambiguous-reversed-operator -fstack-protector-all -fPIC -fno-strict-aliasing -pipe -Wall -W -Wno-unused-parameter -Wno-switch -Wno-missi
ng-field-initializers -Wno-sign-compare -Wno-deprecated -pthread -std=gnu++20 -MD -MT Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/group/GroupInstanceCustomImpl.cpp.o -MF Telegram/CMakeFiles/lib_tgcalls.dir/T
hirdParty/tgcalls/tgcalls/group/GroupInstanceCustomImpl.cpp.o.d -o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/group/GroupInstanceCustomImpl.cpp.o -c /usr/ports/pobj/tdesktop-3.5.0/tdesktop-3.5.0-full/Telegr
am/ThirdParty/tgcalls/tgcalls/group/GroupInstanceCustomImpl.cpp                                                  
/usr/ports/pobj/tdesktop-3.5.0/tdesktop-3.5.0-full/Telegram/ThirdParty/tgcalls/tgcalls/group/GroupInstanceCustomImpl.cpp:31:10: fatal error: 'modules/audio_processing/agc2/vad_wrapper.h' file not found
#include "modules/audio_processing/agc2/vad_wrapper.h"                                                           
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                           
1 error generated.
```

**Comment by mymedia2** [comment]
it looks you have to build the newest tdesktop against tg_owt from the `drm` branch
https://github.com/desktop-app/tg_owt/tree/drm

**Comment by catdevnull** [comment]
Same, https://gitlab.alpinelinux.org/Nulo/aports/-/jobs/614715

I believe they pushed it to master now. However, it seems tg_owt has new dependencies: GBM (from mesa), libdrm and libepoxy.

**Comment by klemensn** [comment]
Yup, `dev` is broken as well: https://github.com/telegramdesktop/tdesktop/runs/5023493462?check_suite_focus=true#step:6:1633

**Comment by catdevnull** [comment]
Using master and adding the dependencies seems to work: https://gitlab.alpinelinux.org/Nulo/aports/-/jobs/615162

**Comment by catdevnull** [comment]
Oh, it's because it's a Qt6 file and Alpine uses Qt5... https://code.woboq.org/qt6/qtbase/include/QtGui/6.2.0/QtGui/private/qaction_p.h.html

**Comment by h0tc0d3** [comment]
Compilation the telegram with clang 13 In Arch Linux fails too.
```
main_window_linux.cpp:50:10: fatal error: 'private/qaction_p.h' file not found
```

**Comment by ilya-fedin** [comment]
Oh, building with Qt 5 is not tested for a long time, so it's apparently the time for guys to package Qt 6 and switch tdesktop to it

**Comment by h0tc0d3** [comment]
@ilya-fedin I use qt6. 
```
'qt6-imageformats' 'qt6-svg' 'qt6-wayland' 'qt6-5compat'
```

**Comment by catdevnull** [comment]
@ptrcnull Weird... When using Qt5, [it was installed automatically](https://gitlab.alpinelinux.org/Nulo/aports/-/jobs/615170#L3692) but [failed anyway](https://gitlab.alpinelinux.org/Nulo/aports/-/jobs/615170#L4685).. I got it to build with Qt6 now, so :shrug:

**Comment by ilya-fedin** [comment]
> @ilya-fedin I use qt6.

It's weird, then...

**Comment by catdevnull** [comment]
> Oh, building with Qt 5 on Linux is not tested for a long time, so it's apparently the time for you guys to package Qt 6 and switch tdesktop to it

Qt6 was packaged already, I just stumbled upon some issues when trying to build tdesktop with it.

**Comment by ilya-fedin** [comment]
> Qt6 was packaged already, I just stumbled upon some issues when trying to build tdesktop with it.

Which issues? :thinking:

**Comment by klemensn** [comment]
OK, after working around another Linux-specific thing in tg_owt, I managed to build its latest version.
Then i rebuilt tdesktop 3.5.0 release against latest tg_owt and the initial error is gone (tg_owt now ships the missing header).

> Compilation the telegram with clang 13 In Arch Linux fails too.
> 
> ```
> main_window_linux.cpp:50:10: fatal error: 'private/qaction_p.h' file not found
> ```

Now I see the same on OpenBSD using Qt5.
The header does exist, but it isn't included/found.
```
$ pkglocate private/qaction_p.h
qt3d-5.15.2p0:x11/qt5/qt3d,-main:/usr/local/include/X11/qt5/Qt3DInput/5.15.2/Qt3DInput/private/qaction_p.h
qt6-qtbase-6.0.4p3:x11/qt6/qtbase,-main:/usr/local/include/X11/qt6/QtGui/6.0.4/QtGui/private/qaction_p.h
qtbase-5.15.2p7:x11/qt5/qtbase,-main:/usr/local/include/X11/qt5/QtWidgets/5.15.2/QtWidgets/private/qaction_p.h
```

**Comment by ilya-fedin** [comment]
> Now I see the same on OpenBSD using Qt5.

Building tdesktop with Qt 6 should fix it

**Comment by klemensn** [comment]
> > Now I see the same on OpenBSD using Qt5.
> 
> Building tdesktop with Qt 6 should fix it

That just fails differently:
```
/usr/ports/pobj/tdesktop-3.5.0/tdesktop-3.5.0-full/Telegram/lib_base/base/network_reachability.cpp:12:10: fatal error: 'QtNetwork/QNetworkInformation' file not found
```

No idea why OpenBSD's qt6-qtbase package does not ship this header, but it's also the first time I'm trying to build tdesktop against Qt6.

**Comment by ilya-fedin** [comment]
> No idea why OpenBSD's qt6-qtbase package does not ship this header

Your Qt 6 version is too old, this class is present only since Qt 6.2

**Comment by klemensn** [comment]
> > No idea why OpenBSD's qt6-qtbase package does not ship this header
> 
> Your Qt 6 version is too old, this class is present only since Qt 6.2

Shouldn't
https://github.com/desktop-app/lib_base/blob/5565b690761e63bafebb391b620a26be3bdfed32/base/network_reachability.cpp#L11
check for `>= 6.2.0`, then?

If I do that, it fails to find the other header as well, since OpenBSD's `qt6-qtbase-6.0.4p3` package ships neither of them.
`<QtNetwork/QNetworkConfigurationManager>` is shipped with our Qt5 package, though, so that way it builds (until hitting the error earlier).

**Comment by ilya-fedin** [comment]
> Shouldn't
> https://github.com/desktop-app/lib_base/blob/5565b690761e63bafebb391b620a26be3bdfed32/base/network_reachability.cpp#L11
> check for `>= 6.2.0`, then?

There's replacement for this class between 5.15 and 6.2, so supporting these versions would be a headache

**Comment by klemensn** [comment]
https://github.com/desktop-app/cmake_helpers/pull/177
Here is the fix for building 3.5.0 against Qt5.

**Comment by h0tc0d3** [comment]
Another error:

```
[ 53%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/api/api_hash.cpp.o
[ 53%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/api/api_polls.cpp.o
[ 53%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/api/api_sending.cpp.o
In file included from <built-in>:485:
In file included from /build/telegram-desktop/src/build/Telegram/CMakeFiles/Telegram.dir/cmake_pch.hxx:5:
In file included from /build/telegram-desktop/src/tdesktop-3.5.0-full/Telegram/SourceFiles/stdafx.h:102:
In file included from /usr/include/range/v3/all.hpp:17:
In file included from /usr/include/range/v3/action.hpp:32:
In file included from /usr/include/range/v3/action/split.hpp:28:
/usr/include/range/v3/range/conversion.hpp:379:29: error: alias template 'QVector' requires template arguments; argument deduction only allowed for class templates
                -> decltype(ContT(range_cpp17_iterator_t<Rng>{},
                            ^
/usr/include/meta/meta.hpp:541:5: note: in instantiation of template class 'ranges::detail::from_range<QVector>' requested here
    using invoke = typename Fn::template invoke<Args...>;
    ^
/usr/include/range/v3/range/conversion.hpp:46:13: note: in instantiation of template type alias 'invoke' requested here
            using container_t = meta::invoke<MetaFn, Rng>;
            ^
/usr/include/range/v3/range/conversion.hpp:338:46: note: in instantiation of template type alias 'container_t' requested here
                    convertible_to_cont<Rng, container_t<MetaFn, Rng>>)
                                             ^
/usr/include/range/v3/detail/prologue.hpp:35:26: note: expanded from macro 'template'
    template<__VA_ARGS__ CPP_TEMPLATE_AUX_                                                               ^
/usr/include/range/v3/range/conversion.hpp:304:13: note: in instantiation of template class 'ranges::detail::to_container::fn<ranges::detail::from_range<QVector>>' requested here
          , Fn
            ^
/usr/include/range/v3/range/conversion.hpp:425:20: note: in instantiation of template class 'ranges::detail::to_container::closure<ranges::detail::from_range<QVector>, ranges::detail::to_container::fn<ranges::detail::from_range<QVector>>>' requested here
            return detail::to_container_fn<detail::from_range<ContT>>{}(
                   ^
/build/telegram-desktop/src/tdesktop-3.5.0-full/Telegram/SourceFiles/api/api_media.cpp:86:12: note: in instantiation of function template specialization 'ranges::_to_::to<QVector, std::vector<tl::boxed<MTPinputDocument>> &>' requested here
                        ranges::to<QVector>(info.attachedStickers)),
                                ^
/usr/include/qt6/QtCore/qcontainerfwd.h:63:22: note: template is declared here
template<typename T> using QVector = QList<T>;
                     ^
In file included from <built-in>:485:
In file included from /build/telegram-desktop/src/build/Telegram/CMakeFiles/Telegram.dir/cmake_pch.hxx:5:
In file included from /build/telegram-desktop/src/tdesktop-3.5.0-full/Telegram/SourceFiles/stdafx.h:102:
In file included from /usr/include/range/v3/all.hpp:17:
In file included from /usr/include/range/v3/action.hpp:32:
In file included from /usr/include/range/v3/action/split.hpp:28:
/usr/include/range/v3/range/conversion.hpp:425:20: error: type 'detail::to_container_fn<detail::from_range<QVector>>' (aka 'closure<ranges::detail::from_range<QVector>, ranges::detail::to_container::fn<ranges::detail::from_range<QVector>>>') does not provide a call operator
            return detail::to_container_fn<detail::from_range<ContT>>{}(
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/telegram-desktop/src/tdesktop-3.5.0-full/Telegram/SourceFiles/api/api_media.cpp:86:12: note: in instantiation of function template specialization 'ranges::_to_::to<QVector, std::vector<tl::boxed<MTPinputDocument>> &>' requested here
                        ranges::to<QVector>(info.attachedStickers)),
                                ^
2 errors generated.
make[2]: *** [Telegram/CMakeFiles/Telegram.dir/build.make:493: Telegram/CMakeFiles/Telegram.dir/SourceFiles/api/api_media.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1550: Telegram/CMakeFiles/Telegram.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Build failed, check /build
```

**Comment by Aokromes** [comment]
but... why you are trying to build with qt5 instead 6.2? this doesn't looks to me a bug on telegram desktop.

**Comment by klemensn** [comment]
> but... why you are trying to build with qt5 instead 6.2? this doesn't looks to me a bug on telegram desktop.

On OpenBSD the Qt6 packages are not yet up to date.
There was in fact a bug in tdesktop's (or rather cmake_helper's) Qt5 header inclusion that was fixed.

3.5.0 builds and works now, so I'm closing the issue.
Thanks for all the insights.
