### ISSUE TITLE
LibreSSL Support

### ISSUE THREAD

**Issue by hadi77ir** [telegramdesktop/tdesktop#3027]
LibreSSL is a compatible fork of OpenSSL which you can use to compile Telegram Desktop with.
It is a fork by OpenBSD project, with goal of refactoring the code .It was created as a response to the Heartbleed vulnerability.
To this date, it has had less vulnerabilities compared to OpenSSL, because it has better code audit than OpenSSL.

Please provide proper compile instructions for using LibreSSL with Telegram Desktop.

**Comment by john-preston** [comment]
@hadi77ir I think it is for the community of libressl users to provide such instructions. Will it work well in Qt instead of openssl? Because Qt treats openssl dependency in a special way.

**Comment by hadi77ir** [comment]
@john-preston Yeah, I tested Qt 5.6.2 compilation with LibreSSL with a few patches (from Gentoo mailing list) and it worked well, but I didn't build Telegram Desktop, as it relied too much on GYP and I was not (and still am not) familiar with it.

Some of dependencies have forks that are better in terms of security and code refactoring, which can be used in Telegram Desktop, for example:
Libav is a fork of FFmpeg with goal of having better code documentation and refactoring.

Also, instead of using VS2015 as the ONLY toolchain for Windows, we may have MinGW-W64 too, as many people really don't have Windows and just want to cross-compile the project.

**Comment by hasufell** [comment]
This is the most trivial patch: https://github.com/Francesco149/better-tdesktop/commit/fdcde306756d405455d295b6056f5ac1d579291a

**Comment by Cogitri** [comment]
As of tdesktop 1.2.1 this patch doesn't work anymore ( with libressl 2.6.x):
```/var/tmp/paludis/build/net-im-telegram-desktop-1.2.1/work/telegram-desktop-1.2.1/Telegram/SourceFiles/mtproto/rsa_public_key.cpp: In constructor 'MTP::internal::RSAPublicKey::Private::Private(base::const_byte_span, base::const_byte_span)':
/var/tmp/paludis/build/net-im-telegram-desktop-1.2.1/work/telegram-desktop-1.2.1/Telegram/SourceFiles/mtproto/rsa_public_key.cpp:119:9: error: 'RSA_set0_key' was not declared in this scope
    if (!RSA_set0_key(_rsa, n, e, nullptr) || !valid) {
         ^~~~~~~~~~~~
/var/tmp/paludis/build/net-im-telegram-desktop-1.2.1/work/telegram-desktop-1.2.1/Telegram/SourceFiles/mtproto/rsa_public_key.cpp:119:9: note: suggested alternative: 'RSA_check_key'
    if (!RSA_set0_key(_rsa, n, e, nullptr) || !valid) {
         ^~~~~~~~~~~~
         RSA_check_key
/var/tmp/paludis/build/net-im-telegram-desktop-1.2.1/work/telegram-desktop-1.2.1/Telegram/SourceFiles/mtproto/rsa_public_key.cpp: In member function 'base::byte_vector MTP::internal::RSAPublicKey::Private::getN() const':
/var/tmp/paludis/build/net-im-telegram-desktop-1.2.1/work/telegram-desktop-1.2.1/Telegram/SourceFiles/mtproto/rsa_public_key.cpp:129:3: error: 'RSA_get0_key' was not declared in this scope
   RSA_get0_key(_rsa, &n, nullptr, nullptr);
   ^~~~~~~~~~~~
/var/tmp/paludis/build/net-im-telegram-desktop-1.2.1/work/telegram-desktop-1.2.1/Telegram/SourceFiles/mtproto/rsa_public_key.cpp:129:3: note: suggested alternative: 'RSA_check_key'
   RSA_get0_key(_rsa, &n, nullptr, nullptr);
   ^~~~~~~~~~~~
   RSA_check_key
/var/tmp/paludis/build/net-im-telegram-desktop-1.2.1/work/telegram-desktop-1.2.1/Telegram/SourceFiles/mtproto/rsa_public_key.cpp: In member function 'base::byte_vector MTP::internal::RSAPublicKey::Private::getE() const':
/var/tmp/paludis/build/net-im-telegram-desktop-1.2.1/work/telegram-desktop-1.2.1/Telegram/SourceFiles/mtproto/rsa_public_key.cpp:135:3: error: 'RSA_get0_key' was not declared in this scope
   RSA_get0_key(_rsa, nullptr, &e, nullptr);
   ^~~~~~~~~~~~
/var/tmp/paludis/build/net-im-telegram-desktop-1.2.1/work/telegram-desktop-1.2.1/Telegram/SourceFiles/mtproto/rsa_public_key.cpp:135:3: note: suggested alternative: 'RSA_check_key'
   RSA_get0_key(_rsa, nullptr, &e, nullptr);
   ^~~~~~~~~~~~
   RSA_check_key
/var/tmp/paludis/build/net-im-telegram-desktop-1.2.1/work/telegram-desktop-1.2.1/Telegram/SourceFiles/mtproto/rsa_public_key.cpp: In member function 'void MTP::internal::RSAPublicKey::Private::computeFingerprint()':
/var/tmp/paludis/build/net-im-telegram-desktop-1.2.1/work/telegram-desktop-1.2.1/Telegram/SourceFiles/mtproto/rsa_public_key.cpp:188:3: error: 'RSA_get0_key' was not declared in this scope
   RSA_get0_key(_rsa, &n, &e, nullptr);
   ^~~~~~~~~~~~
/var/tmp/paludis/build/net-im-telegram-desktop-1.2.1/work/telegram-desktop-1.2.1/Telegram/SourceFiles/mtproto/rsa_public_key.cpp:188:3: note: suggested alternative: 'RSA_check_key'
   RSA_get0_key(_rsa, &n, &e, nullptr);
   ^~~~~~~~~~~~
   RSA_check_key
```

**Comment by Cogitri** [comment]
Seems like this is pretty much caused by #4061
