### ISSUE TITLE
Build failure against Qt 5.9.0

### ISSUE THREAD

**Issue by xvitaly** [telegramdesktop/tdesktop#3379]
### Steps to reproduce
1. Build using systemwide Qt 5.9.0.
2. 
3. 

### Expected behaviour
Normal build.

### Actual behaviour
Build failure:
```c++
[ 63%] Building CXX object CMakeFiles/Telegram.dir/builddir/build/BUILD/tdesktop-1.0.37/Telegram/SourceFiles/storage/localstorage.o
In file included from /usr/include/qt5/QtCore/QtCore:4:0,
                 from /builddir/build/BUILD/tdesktop-1.0.37/out/Release/Telegram_pch/stdafx.h:42:
/usr/include/qt5/QtCore/qflags.h: In instantiation of 'class QFlags<QFlags<MTPDstickerSet::Flag> >':
/builddir/build/BUILD/tdesktop-1.0.37/Telegram/SourceFiles/storage/localstorage.cpp:3274:94:   required from here
/usr/include/qt5/QtCore/qglobal.h:733:47: error: static assertion failed: QFlags is only usable on enumeration types.
 #define Q_STATIC_ASSERT_X(Condition, Message) static_assert(bool(Condition), Message)
                                               ^
/usr/include/qt5/QtCore/qflags.h:96:5: note: in expansion of macro 'Q_STATIC_ASSERT_X'
     Q_STATIC_ASSERT_X((std::is_enum<Enum>::value), "QFlags is only usable on enumeration types.");
     ^~~~~~~~~~~~~~~~~
In file included from /usr/include/qt5/QtCore/qglobal.h:45:0,
                 from /usr/include/qt5/QtCore/QtCore:4,
                 from /builddir/build/BUILD/tdesktop-1.0.37/out/Release/Telegram_pch/stdafx.h:42:
/usr/include/c++/7/type_traits: In instantiation of 'struct std::underlying_type<QFlags<MTPDstickerSet::Flag> >':
/usr/include/qt5/QtCore/qflags.h:112:17:   required from 'class QFlags<QFlags<MTPDstickerSet::Flag> >'
/builddir/build/BUILD/tdesktop-1.0.37/Telegram/SourceFiles/storage/localstorage.cpp:3274:94:   required from here
/usr/include/c++/7/type_traits:2245:38: error: 'QFlags<MTPDstickerSet::Flag>' is not an enumeration type
       typedef __underlying_type(_Tp) type;
                                      ^~~~
/builddir/build/BUILD/tdesktop-1.0.37/Telegram/SourceFiles/storage/localstorage.cpp: In function 'void Local::_readStickerSets(Local::{anonymous}::FileKey&, Stickers::Order*, MTPDstickerSet::Flags)':
/builddir/build/BUILD/tdesktop-1.0.37/Telegram/SourceFiles/storage/localstorage.cpp:3274:13: error: no match for 'operator|=' (operand types are 'qint32 {aka int}' and 'QFlags<QFlags<MTPDstickerSet::Flag> >')
    setFlags |= qFlags(MTPDstickerSet::Flag::f_official | MTPDstickerSet_ClientFlag::f_special);
    ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/qt5/QtCore/QtCore:184:0,
                 from /builddir/build/BUILD/tdesktop-1.0.37/out/Release/Telegram_pch/stdafx.h:42:
/usr/include/qt5/QtCore/qurl.h:388:33: note: candidate: QUrl::FormattingOptions& operator|=(QUrl::FormattingOptions&, QUrl::ComponentFormattingOptions)
 inline QUrl::FormattingOptions &operator|=(QUrl::FormattingOptions &i, QUrl::ComponentFormattingOptions f)
                                 ^~~~~~~~
/usr/include/qt5/QtCore/qurl.h:388:33: note:   no known conversion for argument 2 from 'QFlags<QFlags<MTPDstickerSet::Flag> >' to 'QUrl::ComponentFormattingOptions {aka QFlags<QUrl::ComponentFormattingOption>}'
In file included from /builddir/build/BUILD/tdesktop-1.0.37/out/Release/../../Telegram/SourceFiles/mtproto/facade.h:23:0,
                 from /builddir/build/BUILD/tdesktop-1.0.37/out/Release/Telegram_pch/stdafx.h:65:
/builddir/build/BUILD/tdesktop-1.0.37/out/Release/../../Telegram/SourceFiles/mtproto/core_types.h:918:21: note: candidate: MTPDmessage::Flags& operator|=(MTPDmessage::Flags&, MTPDmessage_ClientFlag)
 inline Type::Flags &operator|=(Type::Flags &i, Type##_ClientFlag v) { return i |= qFlags(v); } \
                     ^
/builddir/build/BUILD/tdesktop-1.0.37/out/Release/../../Telegram/SourceFiles/mtproto/core_types.h:918:21: note: in definition of macro 'DEFINE_MTP_CLIENT_FLAGS'
 inline Type::Flags &operator|=(Type::Flags &i, Type##_ClientFlag v) { return i |= qFlags(v); } \
                     ^~~~~~~~
/builddir/build/BUILD/tdesktop-1.0.37/out/Release/../../Telegram/SourceFiles/mtproto/core_types.h:918:21: note:   no known conversion for argument 1 from 'qint32 {aka int}' to 'MTPDmessage::Flags& {aka QFlags<MTPDmessage::Flag>&}'
 inline Type::Flags &operator|=(Type::Flags &i, Type##_ClientFlag v) { return i |= qFlags(v); } \
                     ^
/builddir/build/BUILD/tdesktop-1.0.37/out/Release/../../Telegram/SourceFiles/mtproto/core_types.h:918:21: note: in definition of macro 'DEFINE_MTP_CLIENT_FLAGS'
 inline Type::Flags &operator|=(Type::Flags &i, Type##_ClientFlag v) { return i |= qFlags(v); } \
                     ^~~~~~~~
/builddir/build/BUILD/tdesktop-1.0.37/out/Release/../../Telegram/SourceFiles/mtproto/core_types.h:918:21: note: candidate: MTPDreplyKeyboardMarkup::Flags& operator|=(MTPDreplyKeyboardMarkup::Flags&, MTPDreplyKeyboardMarkup_ClientFlag)
 inline Type::Flags &operator|=(Type::Flags &i, Type##_ClientFlag v) { return i |= qFlags(v); } \
                     ^
/builddir/build/BUILD/tdesktop-1.0.37/out/Release/../../Telegram/SourceFiles/mtproto/core_types.h:918:21: note: in definition of macro 'DEFINE_MTP_CLIENT_FLAGS'
 inline Type::Flags &operator|=(Type::Flags &i, Type##_ClientFlag v) { return i |= qFlags(v); } \
                     ^~~~~~~~
/builddir/build/BUILD/tdesktop-1.0.37/out/Release/../../Telegram/SourceFiles/mtproto/core_types.h:918:21: note:   no known conversion for argument 1 from 'qint32 {aka int}' to 'MTPDreplyKeyboardMarkup::Flags& {aka QFlags<MTPDreplyKeyboardMarkup::Flag>&}'
 inline Type::Flags &operator|=(Type::Flags &i, Type##_ClientFlag v) { return i |= qFlags(v); } \
                     ^
/builddir/build/BUILD/tdesktop-1.0.37/out/Release/../../Telegram/SourceFiles/mtproto/core_types.h:918:21: note: in definition of macro 'DEFINE_MTP_CLIENT_FLAGS'
 inline Type::Flags &operator|=(Type::Flags &i, Type##_ClientFlag v) { return i |= qFlags(v); } \
                     ^~~~~~~~
/builddir/build/BUILD/tdesktop-1.0.37/out/Release/../../Telegram/SourceFiles/mtproto/core_types.h:918:21: note: candidate: MTPDstickerSet::Flags& operator|=(MTPDstickerSet::Flags&, MTPDstickerSet_ClientFlag)
 inline Type::Flags &operator|=(Type::Flags &i, Type##_ClientFlag v) { return i |= qFlags(v); } \
                     ^
/builddir/build/BUILD/tdesktop-1.0.37/out/Release/../../Telegram/SourceFiles/mtproto/core_types.h:918:21: note: in definition of macro 'DEFINE_MTP_CLIENT_FLAGS'
 inline Type::Flags &operator|=(Type::Flags &i, Type##_ClientFlag v) { return i |= qFlags(v); } \
                     ^~~~~~~~
/builddir/build/BUILD/tdesktop-1.0.37/out/Release/../../Telegram/SourceFiles/mtproto/core_types.h:918:21: note:   no known conversion for argument 1 from 'qint32 {aka int}' to 'MTPDstickerSet::Flags& {aka QFlags<MTPDstickerSet::Flag>&}'
 inline Type::Flags &operator|=(Type::Flags &i, Type##_ClientFlag v) { return i |= qFlags(v); } \
                     ^
/builddir/build/BUILD/tdesktop-1.0.37/out/Release/../../Telegram/SourceFiles/mtproto/core_types.h:918:21: note: in definition of macro 'DEFINE_MTP_CLIENT_FLAGS'
 inline Type::Flags &operator|=(Type::Flags &i, Type##_ClientFlag v) { return i |= qFlags(v); } \
                     ^~~~~~~~
In file included from /usr/include/qt5/QtCore/qglobal.h:1151:0,
                 from /usr/include/qt5/QtCore/QtCore:4,
                 from /builddir/build/BUILD/tdesktop-1.0.37/out/Release/Telegram_pch/stdafx.h:42:
/usr/include/qt5/QtCore/qflags.h: In instantiation of 'constexpr QFlags<T>::QFlags(Enum) [with Enum = QFlags<MTPDstickerSet::Flag>]':
/builddir/build/BUILD/tdesktop-1.0.37/out/Release/../../Telegram/SourceFiles/core/utils.h:236:23:   required from 'constexpr QFlags<T> qFlags(Enum) [with Enum = QFlags<MTPDstickerSet::Flag>]'
/builddir/build/BUILD/tdesktop-1.0.37/Telegram/SourceFiles/storage/localstorage.cpp:3274:94:   required from here
/usr/include/qt5/QtCore/qflags.h:120:69: error: using invalid field 'QFlags<T>::i'
     Q_DECL_CONSTEXPR inline QFlags(Enum f) Q_DECL_NOTHROW : i(Int(f)) {}
                                                                     ^
make[2]: *** [CMakeFiles/Telegram.dir/build.make:5145: CMakeFiles/Telegram.dir/builddir/build/BUILD/tdesktop-1.0.37/Telegram/SourceFiles/storage/localstorage.o] Error 1
```

### Configuration
**Operating system:** Fedora

**Version of Telegram Desktop:** 1.0.37 alpha

**Used theme**: n/a
