### ISSUE TITLE
4.7.0 build error due to glibmm 2.76

### ISSUE THREAD

**Issue by xvitaly** [telegramdesktop/tdesktop#26064]
### Steps to reproduce

Run standard packaged build.

### Expected behaviour

Successful build.

### Actual behaviour

Build failure:

```c++
[268/1288] /usr/bin/g++ -DCRL_USE_COMMON_QUEUE -DDESKTOP_APP_DISABLE_CRASH_REPORTS -DDESKTOP_APP_USE_PACKAGED -DKCOREADDONS_EXPORT="" -DQT_CORE5COMPAT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_DEPRECATED_WARNINGS_SINCE=0x051500 -DQT_GUI_LIB -DQT_IMPLICIT_QCHAR_CONSTRUCTION -DQT_NETWORK_LIB -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_OPENGLWIDGETS_LIB -DQT_OPENGL_LIB -DQT_QMLINTEGRATION_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICKWIDGETS_LIB -DQT_QUICK_LIB -DQT_SVG_LIB -DQT_WAYLANDCOMPOSITOR_LIB -DQT_WIDGETS_LIB -I/builddir/build/BUILD/tdesktop-4.7.0-full/Telegram/lib_base -I/builddir/build/BUILD/tdesktop-4.7.0-full/redhat-linux-build/Telegram/lib_base -I/builddir/build/BUILD/tdesktop-4.7.0-full/Telegram/lib_rpl -I/builddir/build/BUILD/tdesktop-4.7.0-full/Telegram/lib_crl -isystem /usr/include/qt6/QtCore -isystem /usr/include/qt6 -isystem /usr/lib64/qt6/mkspecs/linux-g++ -isystem /usr/include/qt6/QtCore/6.4.2 -isystem /usr/include/qt6/QtCore/6.4.2/QtCore -isystem /usr/include/qt6/QtCore5Compat -isystem /usr/include/qt6/QtGui -isystem /usr/include/qt6/QtGui/6.4.2 -isystem /usr/include/qt6/QtGui/6.4.2/QtGui -isystem /usr/include/qt6/QtOpenGL -isystem /usr/include/qt6/QtWidgets -isystem /usr/include/qt6/QtWidgets/6.4.2 -isystem /usr/include/qt6/QtWidgets/6.4.2/QtWidgets -isystem /usr/include/qt6/QtOpenGLWidgets -isystem /usr/include/qt6/QtNetwork -isystem /usr/include/qt6/QtSvg -isystem /usr/include/qt6/QtDBus -isystem /usr/include/qt6/QtQml -isystem /usr/include/qt6/QtQmlIntegration -isystem /usr/include/qt6/QtQuick -isystem /usr/include/qt6/QtQmlModels -isystem /usr/include/qt6/QtQuickWidgets -isystem /usr/include/qt6/QtWaylandCompositor -isystem /usr/share -isystem /builddir/build/BUILD/tdesktop-4.7.0-full/Telegram/ThirdParty/kcoreaddons/src/lib/io -isystem /builddir/build/BUILD/tdesktop-4.7.0-full/Telegram/ThirdParty/kcoreaddons/src/lib/util -isystem /builddir/build/BUILD/tdesktop-4.7.0-full/cmake/external/kcoreaddons/headers/public -isystem /usr/include/giomm-2.68 -isystem /usr/lib64/giomm-2.68/include -isystem /usr/include/glib-2.0 -isystem /usr/lib64/glib-2.0/include -isystem /usr/include/sysprof-4 -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/glibmm-2.68 -isystem /usr/lib64/glibmm-2.68/include -isystem /usr/include/sigc++-3.0 -isystem /usr/lib64/sigc++-3.0/include -O2 -flto=auto -ffat-lto-objects -fexceptions -g1 -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DNDEBUG -std=gnu++20 -fPIC -fno-strict-aliasing -pipe -Wall -Wextra -Wno-unused-parameter -Wno-switch -Wno-maybe-uninitialized -Wno-missing-field-initializers -Wno-sign-compare -Wno-deprecated -pthread -Winvalid-pch -include /builddir/build/BUILD/tdesktop-4.7.0-full/redhat-linux-build/Telegram/lib_base/CMakeFiles/lib_base.dir/cmake_pch.hxx -MD -MT Telegram/lib_base/CMakeFiles/lib_base.dir/base/platform/linux/base_url_scheme_linux.cpp.o -MF Telegram/lib_base/CMakeFiles/lib_base.dir/base/platform/linux/base_url_scheme_linux.cpp.o.d -o Telegram/lib_base/CMakeFiles/lib_base.dir/base/platform/linux/base_url_scheme_linux.cpp.o -c /builddir/build/BUILD/tdesktop-4.7.0-full/Telegram/lib_base/base/platform/linux/base_url_scheme_linux.cpp
FAILED: Telegram/lib_base/CMakeFiles/lib_base.dir/base/platform/linux/base_url_scheme_linux.cpp.o 
/usr/bin/g++ -DCRL_USE_COMMON_QUEUE -DDESKTOP_APP_DISABLE_CRASH_REPORTS -DDESKTOP_APP_USE_PACKAGED -DKCOREADDONS_EXPORT="" -DQT_CORE5COMPAT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_DEPRECATED_WARNINGS_SINCE=0x051500 -DQT_GUI_LIB -DQT_IMPLICIT_QCHAR_CONSTRUCTION -DQT_NETWORK_LIB -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_OPENGLWIDGETS_LIB -DQT_OPENGL_LIB -DQT_QMLINTEGRATION_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICKWIDGETS_LIB -DQT_QUICK_LIB -DQT_SVG_LIB -DQT_WAYLANDCOMPOSITOR_LIB -DQT_WIDGETS_LIB -I/builddir/build/BUILD/tdesktop-4.7.0-full/Telegram/lib_base -I/builddir/build/BUILD/tdesktop-4.7.0-full/redhat-linux-build/Telegram/lib_base -I/builddir/build/BUILD/tdesktop-4.7.0-full/Telegram/lib_rpl -I/builddir/build/BUILD/tdesktop-4.7.0-full/Telegram/lib_crl -isystem /usr/include/qt6/QtCore -isystem /usr/include/qt6 -isystem /usr/lib64/qt6/mkspecs/linux-g++ -isystem /usr/include/qt6/QtCore/6.4.2 -isystem /usr/include/qt6/QtCore/6.4.2/QtCore -isystem /usr/include/qt6/QtCore5Compat -isystem /usr/include/qt6/QtGui -isystem /usr/include/qt6/QtGui/6.4.2 -isystem /usr/include/qt6/QtGui/6.4.2/QtGui -isystem /usr/include/qt6/QtOpenGL -isystem /usr/include/qt6/QtWidgets -isystem /usr/include/qt6/QtWidgets/6.4.2 -isystem /usr/include/qt6/QtWidgets/6.4.2/QtWidgets -isystem /usr/include/qt6/QtOpenGLWidgets -isystem /usr/include/qt6/QtNetwork -isystem /usr/include/qt6/QtSvg -isystem /usr/include/qt6/QtDBus -isystem /usr/include/qt6/QtQml -isystem /usr/include/qt6/QtQmlIntegration -isystem /usr/include/qt6/QtQuick -isystem /usr/include/qt6/QtQmlModels -isystem /usr/include/qt6/QtQuickWidgets -isystem /usr/include/qt6/QtWaylandCompositor -isystem /usr/share -isystem /builddir/build/BUILD/tdesktop-4.7.0-full/Telegram/ThirdParty/kcoreaddons/src/lib/io -isystem /builddir/build/BUILD/tdesktop-4.7.0-full/Telegram/ThirdParty/kcoreaddons/src/lib/util -isystem /builddir/build/BUILD/tdesktop-4.7.0-full/cmake/external/kcoreaddons/headers/public -isystem /usr/include/giomm-2.68 -isystem /usr/lib64/giomm-2.68/include -isystem /usr/include/glib-2.0 -isystem /usr/lib64/glib-2.0/include -isystem /usr/include/sysprof-4 -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/glibmm-2.68 -isystem /usr/lib64/glibmm-2.68/include -isystem /usr/include/sigc++-3.0 -isystem /usr/lib64/sigc++-3.0/include -O2 -flto=auto -ffat-lto-objects -fexceptions -g1 -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DNDEBUG -std=gnu++20 -fPIC -fno-strict-aliasing -pipe -Wall -Wextra -Wno-unused-parameter -Wno-switch -Wno-maybe-uninitialized -Wno-missing-field-initializers -Wno-sign-compare -Wno-deprecated -pthread -Winvalid-pch -include /builddir/build/BUILD/tdesktop-4.7.0-full/redhat-linux-build/Telegram/lib_base/CMakeFiles/lib_base.dir/cmake_pch.hxx -MD -MT Telegram/lib_base/CMakeFiles/lib_base.dir/base/platform/linux/base_url_scheme_linux.cpp.o -MF Telegram/lib_base/CMakeFiles/lib_base.dir/base/platform/linux/base_url_scheme_linux.cpp.o.d -o Telegram/lib_base/CMakeFiles/lib_base.dir/base/platform/linux/base_url_scheme_linux.cpp.o -c /builddir/build/BUILD/tdesktop-4.7.0-full/Telegram/lib_base/base/platform/linux/base_url_scheme_linux.cpp
/builddir/build/BUILD/tdesktop-4.7.0-full/Telegram/lib_base/base/platform/linux/base_url_scheme_linux.cpp: In function 'void base::Platform::UnregisterUrlScheme(const UrlSchemeDescriptor&)':
/builddir/build/BUILD/tdesktop-4.7.0-full/Telegram/lib_base/base/platform/linux/base_url_scheme_linux.cpp:176:55: error: 'get_recommended_for_type' is not a member of 'Gio::AppInfo'
  176 |         const auto registeredAppInfos = Gio::AppInfo::get_recommended_for_type(
      |                                                       ^~~~~~~~~~~~~~~~~~~~~~~~
```

### Operating system

Fedora 37

### Version of Telegram Desktop

4.7.0

### Installation source

Other (unofficial) source

**Comment by xvitaly** [comment]
Regression introduced by https://github.com/desktop-app/lib_base/commit/0d37d47eca896005eb0a645e0db461f4dafb317b.

**Comment by xvitaly** [comment]
> You need glibmm 2.76

1. Please update CMake to require this version then.
2. Check this: https://repology.org/project/glibmm/versions - most distributions don't have this version yet.

**Comment by xvitaly** [comment]
> Sorry, but we don't have an established system for cmake_helpers consumers to define minimum supported dependency version, so this couldn't be done.

```
pkg_check_modules(GLIBMM REQUIRED IMPORTED_TARGET "glibmm-2.68>=2.76")
```

**Comment by xvitaly** [comment]
> We can't block other consumers with tdesktop's minimum version.

Add to `Telegram/CMakeLists.txt` something like this:

```cmake
if (GLIBMM_VERSION VERSION_LESS "2.76")
    message(FATAL_ERROR "You need glibmm 2.76 in order to build Telegram Desktop")
endif()
```

**Comment by ilya-fedin** [comment]
I'm not sure, this feels like a hack, I would prefer to manage this like all other dependencies: just don't have a version specified at all. It's consistent now at least..

**Comment by ilya-fedin** [comment]
On other side, lib_base has 2.76+ code as well...
