### ISSUE TITLE
something is wrong with Qt

### ISSUE THREAD

**Issue by fl0at88** [telegramdesktop/tdesktop#5088]
/usr/local/tdesktop/Qt-5.6.2/include/QtGui/5.6.2/QtGui/private/qtextengine_p.h: In member function ‘void QGlyphLayout::clear(int, int)’:
/usr/local/tdesktop/Qt-5.6.2/include/QtGui/5.6.2/QtGui/private/qtextengine_p.h:232:57: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct QFixedPoint’; use assignment or value-initialization instead [-Werror=class-memaccess]
             memset(offsets, 0, (numGlyphs * SpaceNeeded));

**Comment by john-preston** [comment]
@fl0at88 What compiler version do you use?

**Comment by fl0at88** [comment]
@john-preston ,  thanks,  compiler version gcc8-8.1.1  and gcc7-7.3.1

**Comment by john-preston** [comment]
@fl0at88 It works in gcc 7.2.

**Comment by Aokromes** [comment]
https://bugreports.qt.io/browse/QTQAINFRA-2066

**Comment by fl0at88** [comment]
the errors appear in the precompiled header “stdafx.h”
maybe added "-Werror"
