### ISSUE TITLE
Travis is failing...

### ISSUE THREAD

**Issue by auchri** [telegramdesktop/tdesktop#2005]
... because `dee` (required by [libunity](https://aur.archlinux.org/packages/libunity/)) fails to compile.

See https://bugs.launchpad.net/dee/+bug/1579529

Example broken build: https://travis-ci.org/telegramdesktop/tdesktop/jobs/128672902

```
dee-serializable-model.c: In function ‘dee_serializable_model_get_position’:
dee-serializable-model.c:1329:3: error: this ‘while’ clause does not guard... [-Werror=misleading-indentation]
   while (!dee_model_is_last (self, iter) && iter != _iter)
   ^~~~~
dee-serializable-model.c:1331:5: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘while’
     pos++;
     ^~~
cc1: all warnings being treated as errors
```

**Comment by ItachiSan** [comment]
Don't worry, it will not work with the build of QT5.6 anyways :P
If you want, I have a patched dee version.

**Comment by stek29** [comment]
[This issue at libdee bugtracker](https://bugs.launchpad.net/dee/+bug/1579529)

**Comment by auchri** [comment]
@stek29 

![image](https://cloud.githubusercontent.com/assets/5092164/15229479/8a13ed38-1891-11e6-9209-d84755d02464.png)

:wink:

**Comment by auchri** [comment]
@ItachiSan 
Where can I find this patched version? :)

**Comment by ItachiSan** [comment]
Here you have: https://aur.archlinux.org/packages/dee-fixed/

**Comment by auchri** [comment]
@ItachiSan why did you remove the package from aur? :cry:

**Comment by ItachiSan** [comment]
I didn't, it was a request by an Arch maintainer (I think he is):
https://lists.archlinux.org/pipermail/aur-requests/2016-May/011724.html
https://lists.archlinux.org/pipermail/aur-requests/2016-June/012087.html

I said him there are issues building the normal package, but he continued with the deletion saying "the maintainer should fix it"

**Comment by ItachiSan** [comment]
I made a personal repo for Arch packages using the OpenSUSE Open Build Service.
Here there is the *dee* package:
https://build.opensuse.org/package/show/home:ItachiSan:archlinux/dee
If you click on *Download package*, information about how to add its sources will pop out. :smile:

**Comment by auchri** [comment]
@ItachiSan 

`error: failed retrieving file 'dee-1.2.7-8-x86_64.pkg.tar.xz' from download.opensuse.org : Maximum file size exceeded
warning: failed to retrieve some files`

I don't know what the problem is.
