### ISSUE TITLE
Progress regarding packaging of tdesktop in GNU Guix

### ISSUE THREAD

**Issue by raghavgururajan** [telegramdesktop/tdesktop#10113]
While building tdesktop v2.5.1, the build fails with following error:

```
/tmp/guix-build-tdesktop-2.5.1.drv-0/source/Telegram/ThirdParty/tgcalls/tgcalls/group/GroupInstanceImpl.cpp:572:18: error: ‘virtual void tgcalls::{anonymous}::PeerConnectionObserverImpl::OnErrorDemuxingPacket(uint32_t)’ marked ‘override’, but does not override
     virtual void OnErrorDemuxingPacket(uint32_t ssrc) override {
                  ^~~~~~~~~~~~~~~~~~~~~
/tmp/guix-build-tdesktop-2.5.1.drv-0/source/Telegram/ThirdParty/tgcalls/tgcalls/group/GroupInstanceImpl.cpp: In member function ‘void tgcalls::GroupInstanceManager::start()’:
/tmp/guix-build-tdesktop-2.5.1.drv-0/source/Telegram/ThirdParty/tgcalls/tgcalls/group/GroupInstanceImpl.cpp:1211:19: error: ‘struct cricket::MediaEngineDependencies’ has no member named ‘onUnknownAudioSsrc’
         mediaDeps.onUnknownAudioSsrc = [weak](uint32_t ssrc) {
                   ^~~~~~~~~~~~~~~~~~
```

Any ideas on how to rectify this?

**Comment by raghavgururajan** [comment]
I think this error might be caused by https://github.com/desktop-app/tg_owt/issues/42

**Comment by ilya-fedin** [comment]
Looks like you've cloned tg_owt without submodules

**Comment by raghavgururajan** [comment]
@ilya-fedin How do I clone along with the sub-modules? For example, the 'libyuv @ ad89006' entry at https://github.com/desktop-app/tg_owt/tree/master/src/third_party, is not clickable.

**Comment by ilya-fedin** [comment]
Have you read tdesktop build instructions?

**Comment by raghavgururajan** [comment]
@ilya-fedin I looked at this (https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-cmake.md). For my use case, I don't think its applicable. I am packaging tdesktop for Guix (https://guix.gnu.org), which is a non-conventional distro. Also, I think I need to set "-DDESKTOP_APP_USE_PACKAGED" to 'ON'.

Any pointers please. I would like to learn.

**Comment by ilya-fedin** [comment]
Oh. Nix has fetchSubmodules parameter for fetchGit, doesn't Guix have one?

**Comment by raghavgururajan** [comment]
I am not sure. Let me check and get back to you.

**Comment by ilya-fedin** [comment]
> Also, I think I need to set "-DDESKTOP_APP_USE_PACKAGED" to 'ON'.

You shouldn't set anything for packaged build, it's the default...

**Comment by raghavgururajan** [comment]
> > Also, I think I need to set "-DDESKTOP_APP_USE_PACKAGED" to 'ON'.
> 
> You shouldn't set anything for packaged build, it's the default...

Ah yes, you are correct. It was set to 'ON' by default.

**Comment by raghavgururajan** [comment]
> Oh. Nix has fetchSubmodules parameter for fetchGit, doesn't Guix have one?

@ilya-fedin Btw, tg_owt is not a direct sub-module of tdesktop right? I was packaging tg_owt separately, during which I faced, https://github.com/desktop-app/tg_owt/issues/42.

**Comment by ilya-fedin** [comment]
> Btw, tg_owt is not a direct sub-module of tdesktop right?

No, it's too big to have it's as a submodule in tdesktop

**Comment by raghavgururajan** [comment]
> > Btw, tg_owt is not a direct sub-module of tdesktop right?
> 
> No, it's too big to have it as a submodule in tdesktop

I see. All the mentioned sub-modules in tdesktop, I made them available during the build. The only issue I am facing is the error I mentioned.

**Comment by ilya-fedin** [comment]
So, have you set fetchSubmodules?

**Comment by raghavgururajan** [comment]
> > > Btw, tg_owt is not a direct sub-module of tdesktop right?
> > 
> > 
> > No, it's too big to have it as a submodule in tdesktop
> 
> I see. All the mentioned sub-modules in tdesktop, I made them available during the build. The only issue I am facing is the error I mentioned.

To be specific, I am building tdesktop with separately packaged libtgvoip (v2.4.4) and tg_owt (master @ 10b988a).

**Comment by raghavgururajan** [comment]
> So, have you set fetchSubmodules for tg_owt?

Do you mean for tg_owt?

**Comment by ilya-fedin** [comment]
yeah...

**Comment by raghavgururajan** [comment]
@ilya-fedin I just found a way to rebuild tg_owt with submodules. I will get back to you.

**Comment by raghavgururajan** [comment]
@ilya-fedin So I have built tg_owt with the submodules. The old error message is gone. But now I get:
```
/tmp/guix-build-tdesktop-2.5.1.drv-0/source/Telegram/ThirdParty/tgcalls/tgcalls/MediaManager.cpp:272:68: error: ‘MediaTransportConfig’ is not a member of ‘webrtc’
  272 |  _audioChannel->SetInterface(_audioNetworkInterface.get(), webrtc::MediaTransportConfig());
      |                                                                    ^~~~~~~~~~~~~~~~~~~~
/tmp/guix-build-tdesktop-2.5.1.drv-0/source/Telegram/ThirdParty/tgcalls/tgcalls/MediaManager.cpp:286:68: error: ‘MediaTransportConfig’ is not a member of ‘webrtc’
  286 |  _videoChannel->SetInterface(_videoNetworkInterface.get(), webrtc::MediaTransportConfig());
      |                                                                    ^~~~~~~~~~~~~~~~~~~~
/tmp/guix-build-tdesktop-2.5.1.drv-0/source/Telegram/ThirdParty/tgcalls/tgcalls/MediaManager.cpp: In destructor ‘virtual tgcalls::MediaManager::~MediaManager()’:
/tmp/guix-build-tdesktop-2.5.1.drv-0/source/Telegram/ThirdParty/tgcalls/tgcalls/MediaManager.cpp:359:47: error: ‘MediaTransportConfig’ is not a member of ‘webrtc’
  359 |  _audioChannel->SetInterface(nullptr, webrtc::MediaTransportConfig());
      |                                               ^~~~~~~~~~~~~~~~~~~~
/tmp/guix-build-tdesktop-2.5.1.drv-0/source/Telegram/ThirdParty/tgcalls/tgcalls/MediaManager.cpp:382:50: error: ‘MediaTransportConfig’ is not a member of ‘webrtc’
  382 |     _videoChannel->SetInterface(nullptr, webrtc::MediaTransportConfig());
      |                                                  ^~~~~~~~~~~~~~~~~~~~

```

**Comment by raghavgururajan** [comment]
I also see the following error:
```
/tmp/guix-build-tdesktop-2.5.1.drv-0/source/Telegram/ThirdParty/libtgvoip/EchoCanceller.cpp:154:36: error: no matching function for call to ‘webrtc::AudioProcessing::ProcessReverseStream(webrtc::AudioFrame*)’
  154 |    apm->ProcessReverseStream(&frame);
      |                                    ^

```

**Comment by ilya-fedin** [comment]
latest tg_owt is for 2.5.5, if you building 2.5.1, you should build tg_owt from https://github.com/desktop-app/tg_owt/commit/fa86fcc00c218813d61a272a56feab55c76a1ab9

**Comment by ilya-fedin** [comment]
> I also see the following error:

You said the you built libtgvoip as a separate package, but it currently doesn't build separately from tdesktop... So I guess you built it from an old commit that won't build with latest version of tdestkop

**Comment by raghavgururajan** [comment]
> latest tg_owt is for 2.5.5, if you building 2.5.1, you should build tg_owt from [desktop-app/tg_owt@fa86fcc](https://github.com/desktop-app/tg_owt/commit/fa86fcc00c218813d61a272a56feab55c76a1ab9)

@ilya-fedin Ah thanks! Let me retry building with tg_owt at fa86fcc.

**Comment by raghavgururajan** [comment]
> > I also see the following error:
> 
> You said the you built libtgvoip as a separate package, but it currently doesn't build separately from tdesktop... So I guess you built it from an old commit that won't build with latest version of tdestop

@ilya-fedin 
I tried libtgvoip both as submodule (https://github.com/telegramdesktop/libtgvoip/tree/13a5fcb16b04472d808ce122abd695dbf5d206cd) and as separate package (https://github.com/grishka/libtgvoip/releases/tag/2.4.4). Both gave the same error.

**Comment by ilya-fedin** [comment]
libtgvoip from submodule is failing due to too new tg_owt likely, libtgvoip from separate package won't work at all since tdesktop's forks is very different

**Comment by raghavgururajan** [comment]
> libtgvoip from submodule is failing due to too new tg_owt likely, libtgvoip from separate package won't work at all since tdesktop's fork differs a lot

I see. Tg_owt is rebuilding now....

**Comment by ilya-fedin** [comment]
Could the issue be closed?

**Comment by raghavgururajan** [comment]
@ilya-fedin So I have successfully built the tdesktop with test api id. But upon launch, the app crashes with the following:
```
(process:13721): Telegram-WARNING **: 03:56:10.127: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 03:56:10.130: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used,
this will lead to a crash.
Telegram-Message: 03:56:10.130: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).

(process:13721): Telegram-WARNING **: 03:56:10.131: Application was built without embedded fonts, this may lead to font issues.

(.telegram-desktop-real:13721): dbind-WARNING **: 03:56:10.211: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Aborted

```

I do not see any 'errors' though. Any idea on why it may be crashing? Thanks!

**Comment by ilya-fedin** [comment]
Looks like it's Qt's GTK integration (if you disable Telegram's GTK integration, Qt one will work if your DE is based on gtk).

**Comment by raghavgururajan** [comment]
> Looks like it's Qt's GTK integration (if you disable Telegram's GTK integration, Qt one still will work if your DE is based on gtk).

Thanks! Let me rebuild the application with gtk integration disabled.

Btw, regarding embedded fonts, is there a specific dependency? I added all the ones that showed up during configure.

**Comment by raghavgururajan** [comment]
@ilya-fedin So I have rebuilt without gtk integration. The app still crashes with the following:
```
(process:15684): Telegram-WARNING **: 04:52:07.281: GTK integration was disabled on build or in runtime. This will lead to clipboard issues and a lack of some features (like Auto-Night Mode or system window controls layout).

(process:15684): Telegram-WARNING **: 04:52:07.284: Application was built without embedded fonts, this may lead to font issues.
Aborted
```

**Comment by ilya-fedin** [comment]
Quoting myself:

> if you disable Telegram's GTK integration, Qt one still will work if your DE is based on gtk

**Comment by raghavgururajan** [comment]
> Quoting myself:
> 
> > if you disable Telegram's GTK integration, Qt one still will work if your DE is based on gtk
yes, I understood that. I was wondering what makes the app to crash. There was no error message in the terminal.

**Comment by ilya-fedin** [comment]
Maybe it's not, since there's no warnings from GTK now.. Try to get backtrace from gdb.

**Comment by ilya-fedin** [comment]
As far as I know, NixOS has custom qt5.mkDerivation for qt apps that sets some compile-time parameters and adds a wrapper to point Qt to its plugins and other resource. It's also a challenge to update Qt for them every time. So if you packaged Qt in a dumb way, it won't work most likely...

**Comment by raghavgururajan** [comment]
Cool! So this seems to guix specific issue. So I'll close this thread. 

Thank you for the help! :-)
