### ISSUE TITLE
Can't compile with Qt 6.9.0

### ISSUE THREAD

**Issue by Vascom** [telegramdesktop/tdesktop#29181]
### Steps to reproduce

Try to compile tdesktop for Linux.

### Expected behaviour

Successful build

### Actual behaviour

```
/builddir/build/BUILD/telegram-desktop-5.13.1-build/tdesktop-5.13.1-full/Telegram/lib_base/base/platform/linux/base_linux_xdp_utilities.cpp:19:10: fatal error: private/qgenericunixservices_p.h: No such file or directory
   19 | #include <private/qgenericunixservices_p.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Operating system

Fedora Rawhide

### Version of Telegram Desktop

5.13.1.

### Installation source

Static binary from official website

### Logs

```shell

```

**Comment by ilya-fedin** [comment]
Only Dev branch supports Qt 6.9

**Comment by microcai** [comment]
is there going to be a release or a backport ?

**Comment by ilya-fedin** [comment]
Not sure what you mean by backport (backport where?), a release will be as soon as it's ready, there's no strong schedule
