### ISSUE TITLE
Fail to build with newer GLib-1.82.0

### ISSUE THREAD

**Issue by tanuki-no** [telegramdesktop/tdesktop#28609]
### Steps to reproduce

1. Update GLib to 1.82.x
2. Try to build telegram on Linux.

### Expected behaviour

Normal deploy

### Actual behaviour

Compilation failes with the next issue:

`
tdesktop-5.7.1-full/Telegram/lib_webview/webview/platform/linux/webview_linux_webkitgtk.cpp:801:36: error: ‘class gi::repository::Gio::Credentials’ has no member named ‘get_unix_pid’
`

### Operating system

Gentoo Linux/6.11.5/Profile:default/linux/amd64/23.0/no-multilib/systemd (stable)

### Version of Telegram Desktop

5.7.1

### Installation source

Other (unofficial) source

### Logs

```shell
[31/1497] cd /var/tmp/portage/net-im/telegram-desktop-5.7.1/work/tdesktop-5.7.1-full_build/cmake/external/glib && /usr/bin/cppgir --debug 1 --class --class-full --expected --ignore /var/tmp/portage/net-im/telegram-desktop-5.7.1/work/tdesktop-5.7.1-full/cmake/external/glib/cppgir/data/cppgir.ignore:/var/tmp/portage/net-im/telegram-desktop-5.7.1/work/tdesktop-5.7.1-full/cmake/external/glib/cppgir/data/cppgir_unix.ignore --output /var/tmp/portage/net-im/telegram-desktop-5.7.1/work/tdesktop-5.7.1-full_build/gen GioUnix-2.0 && echo 1> /var/tmp/portage/net-im/telegram-desktop-5.7.1/work/tdesktop-5.7.1-full_build/gen/external_glib_cppgir.timestamp
ERROR EXCEPTION processing class DesktopAppInfo; GioUnix::DesktopAppInfo maps to ::GDesktopAppInfo, already claimed by Gio::DesktopAppInfo;
Please verify/fix GIRs and/or add ignore as needed.
ERROR EXCEPTION processing class FDMessage; GioUnix::FDMessage maps to ::GUnixFDMessage, already claimed by Gio::UnixFDMessage;
Please verify/fix GIRs and/or add ignore as needed.
ERROR EXCEPTION processing interface FileDescriptorBased; GioUnix::FileDescriptorBased maps to ::GFileDescriptorBased, already claimed by Gio::FileDescriptorBased;
Please verify/fix GIRs and/or add ignore as needed.
ERROR EXCEPTION processing class InputStream; GioUnix::InputStream maps to ::GUnixInputStream, already claimed by Gio::UnixInputStream;
Please verify/fix GIRs and/or add ignore as needed.
ERROR EXCEPTION processing record MountEntry; GioUnix::MountEntry maps to ::GUnixMountEntry, already claimed by Gio::UnixMountEntry;
Please verify/fix GIRs and/or add ignore as needed.
ERROR EXCEPTION processing class MountMonitor; GioUnix::MountMonitor maps to ::GUnixMountMonitor, already claimed by Gio::UnixMountMonitor;
Please verify/fix GIRs and/or add ignore as needed.
ERROR EXCEPTION processing record MountPoint; GioUnix::MountPoint maps to ::GUnixMountPoint, already claimed by Gio::UnixMountPoint;
Please verify/fix GIRs and/or add ignore as needed.
ERROR EXCEPTION processing class OutputStream; GioUnix::OutputStream maps to ::GUnixOutputStream, already claimed by Gio::UnixOutputStream;
Please verify/fix GIRs and/or add ignore as needed.
```

**Comment by tanuki-no** [comment]
[build.log](https://github.com/user-attachments/files/17617170/build.log)
This is the full build log.

**Comment by volkov-am** [comment]
May be related to https://github.com/telegramdesktop/tdesktop/issues/28454

Try to apply this patch to dev-cpp/cppgir
https://gitlab.com/mnauw/cppgir/-/commit/c8bb1c6017a6f7f2e47bd10543aea6b3ec69a966.patch

This helps me to fix the error
