### ISSUE TITLE
Failed to build on 16.04 ubuntu

### ISSUE THREAD

**Issue by sjames1958gm** [telegramdesktop/tdesktop#3937]
### Steps to reproduce
1. Followed instructions on page to build on linux ubuntu 16.04

### Expected behaviour
It builds

### Actual behaviour
Tell us what happens 

### Configuration
**Operating system:**
Ubuntu 16.04
**Version of Telegram Desktop:**
latest as of Sept 28, 2017
**Used theme**:

The following changes were required to get rid of some errors:

diff --git a/Telegram/ThirdParty/libtgvoip b/Telegram/ThirdParty/libtgvoip
--- a/Telegram/ThirdParty/libtgvoip
+++ b/Telegram/ThirdParty/libtgvoip
@@ -1 +1 @@
-Subproject commit 9f78cb85e5db9b39a6c4c3f7847ea3e98c9f544a
+Subproject commit 9f78cb85e5db9b39a6c4c3f7847ea3e98c9f544a-dirty

**First I had to change the include on libs icutu so that it would look in 
/usr/lib/x86_64-linux-gnu**
diff --git a/Telegram/gyp/qt.gypi b/Telegram/gyp/qt.gypi
index 67f7976..706a004 100644
--- a/Telegram/gyp/qt.gypi
+++ b/Telegram/gyp/qt.gypi
@@ -144,7 +144,7 @@
     'linux_path_xkbcommon%': '/usr/local',
     'linux_lib_ssl%': '/usr/local/ssl/lib/libssl.a',
     'linux_lib_crypto%': '/usr/local/ssl/lib/libcrypto.a',
-    'linux_lib_icu%': '/usr/lib/libicutu.a /usr/lib/libicui18n.a /usr/lib/libicuuc.a /usr/lib/libicudata.a',
+    'linux_lib_icu%': 'icuuc icutu icui18n',
   },
 
   'configurations': {

**Then I added libsndio.so to gyp to get it to pick up -lsndio**

diff --git a/Telegram/gyp/telegram_linux.gypi b/Telegram/gyp/telegram_linux.gypi
index 2c46492..dc63de6 100644
--- a/Telegram/gyp/telegram_linux.gypi
+++ b/Telegram/gyp/telegram_linux.gypi
@@ -43,6 +43,7 @@
       '<(linux_path_opus_include)',
     ],
     'library_dirs': [
+      '/usr/x86_64-linux-gnu',
       '/usr/local/lib',
       '<(linux_path_ffmpeg)/lib',
       '<(linux_path_openal)/lib',
@@ -70,6 +71,7 @@
       'libva.a',
       'libvdpau.a',
       'libdrm.a',
+      'libsndio.so',
       'libz.a',
 #      '<!(pkg-config 2> /dev/null --libs <@(pkgconfig_libs))',
     ],

----------
**This change was needed to pass the gnu++11 flag to lib4gvoip**
diff --git a/libtgvoip.gyp b/libtgvoip.gyp
index 6363d02..9316f05 100644
--- a/libtgvoip.gyp
+++ b/libtgvoip.gyp
@@ -383,7 +383,7 @@
                 'WEBRTC_POSIX',
               ],
               'cflags_cc': [
-                '-msse2',
+                '-msse2 -std=gnu++11',
               ],
               'direct_dependent_settings': {
                 'libraries': [

I am still getting the following error: have not been able to resolve.

/usr/local/tdesktop/Qt-5.6.2/lib/libQt5Network.a(qsslsocket_openssl_symbols.o): In function `q_EC_curve_nist2nid(char const*)':
/home/nzgpu/Development/Telegram/Libraries/qt5_6_2/qtbase/src/network/ssl/qsslsocket_openssl_symbols.cpp:426: undefined reference to `EC_curve_nist2nid'
collect2: error: ld returned 1 exit status
CMakeFiles/Telegram.dir/build.make:12386: recipe for target 'Telegram' failed
make[2]: *** [Telegram] Error 1
CMakeFiles/Makefile2:83: recipe for target 'CMakeFiles/Telegram.dir/all' failed
make[1]: *** [CMakeFiles/Telegram.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by roman-voropaev** [comment]
You have to use Ubuntu 12.04 to build. I'm using Vagrant to run old ubuntu under VirtualBox in Linux Mint 18. If anybody interested I will attach it.

**Comment by roman-voropaev** [comment]
There are also some minor errors in build instructions, I will pull-request them later.

**Comment by john-preston** [comment]
@roman-voropaev You may want to wait a little, soon instructions will be updated for Ubuntu 14.04.

**Comment by roman-voropaev** [comment]
@john-preston What about using virtual machine/isolated container for building linux client in general?
It's common practice (at least in [web dev](https://www.andrewmunsell.com/blog/development-environments-with-vagrant-and-puppet/)). Even after updating to 14.04 few people have dedicated machine with such old Ubuntu version. Also such isolated builds are much more reproducible and flexible - because they can done from scratch several times in a day.
[Vagrant](https://www.vagrantup.com/)+[VirtualBox](https://www.virtualbox.org) provides excellent isolated environment. Here is my [config](https://gist.github.com/roman-voropaev/cd044d9eae76540f5ce3c1d4176fac47). On my machine (i7-3770,16G RAM) dependencies build takes one hour and Telegram itself - half an hour.
OR we may use docker for isolation (it will require less RAM, but more disk space for fs layers). Initially I tried docker, but I had no space left on my disk, so I switched to vagrant. But now I have more disk space, so I can try again.
And yes, I'm looking forward to new build instructions with shorter list of dependencies and build time :smiley_cat:

**Comment by s89162504** [comment]
is everyone sure that build instruction of ubuntu12.04 is correct??

i build step by step but still fail

i got a lot of error like  「undefined reference to `operator delete(void*, unsigned long)'」

and

collect2: error: ld returned 1 exit status

**Comment by sjames1958gm** [comment]
So I decided to use docker and create a 12.04 container and follow the instructions - I got an error trying to build openal-soft. Possibly need to checkout an older version?

CMake Error at CMakeLists.txt:3 (CMAKE_MINIMUM_REQUIRED):
  CMake 3.0.2 or higher is required.  You are running version 2.8.7

I attached my docker file below I had to add .txt extension to attach.

[dockerfile.txt](https://github.com/telegramdesktop/tdesktop/files/1376525/dockerfile.txt)

**Comment by roman-voropaev** [comment]
Yes, there is an order error in instructions - you have to build Cmake first AND install it system-wide, then build openal. See this provision script in my [gist](https://gist.github.com/roman-voropaev/cd044d9eae76540f5ce3c1d4176fac47).

**Comment by auchri** [comment]
@roman-voropaev Why do you not create a PR if you know that there is an error in the instructions? 🤔

**Comment by roman-voropaev** [comment]
@auchri because @john-preston told me that instructions will be updated anyway soon. The plan was to PR new instructions later to avoid merging :smiley: 
Also, what do you think about building Telegram under docker or vagrant? That would make it possible to easily build windows and linux versions on the same machine (if you would like to do so).

**Comment by auchri** [comment]
👍 for docker, I can create a new repo for the Dockerfile if you want. (doesn't belong to the main repo imho). We could then also use this Dockerfile for the build test at travis.

**Comment by roman-voropaev** [comment]
Oh, that sounds great. Then I will try to setup build process via Docker and test it on Windows and Linux this week.

**Comment by auchri** [comment]
@roman-voropaev Awesome!
But I think it's better to wait for the updated build instructions ... else the everything has to be done again with the updated instructions 😕

**Comment by auchri** [comment]
@roman-voropaev I've created a repo here: https://github.com/telegramdesktop/docker

**Comment by roman-voropaev** [comment]
Ok, thanks! I'll be waiting for the new instructions then, meanwhile
practicing with docker toolbox on windows.

*Best Regards, Roman*

2017-10-12 0:11 GMT+03:00 Christoph <notifications@github.com>:

**Comment by roman-voropaev** [comment]
@auchri could you please commit anything like an empty file to https://github.com/telegramdesktop/docker - seems like Github prevents forking empty repositories.
I've finished a draft version for the old instructions. Successfully built on Windows 8 with Docker Toolbox.

**Comment by auchri** [comment]
@roman-voropaev Sure, I've added an empty dockerfile :)
