### ISSUE TITLE
Build failure against Qt < 5.15

### ISSUE THREAD

**Issue by xvitaly** [telegramdesktop/tdesktop#10398]
### Steps to reproduce
1. Build against Qt < 5.15
2. 
3. 

### Expected behaviour
Successful build.

### Actual behaviour
Build failure:
```c++
../Telegram/lib_ui/ui/platform/ui_platform_window_title.cpp: In member function 'virtual void Ui::Platform::DefaultTitleWidget::mouseMoveEvent(QMouseEvent*)':
../Telegram/lib_ui/ui/platform/ui_platform_window_title.cpp:334:29: error: 'class QWindow' has no member named 'startSystemMove'
  334 |   window()->windowHandle()->startSystemMove();
      |                             ^~~~~~~~~~~~~~~
[333/857] /usr/bin/c++  -DDESKTOP_APP_DISABLE_CRASH_REPORTS -DDESKTOP_APP_DISABLE_WAYLAND_INTEGRATION -DDESKTOP_APP_USE_PACKAGED -DDESKTOP_APP_USE_PACKAGED_FONTS -DNDEBUG -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -ITelegram/lib_ui/lib_ui_autogen/include -ITelegram/lib_ui/gen -I../Telegram/lib_ui -I../Telegram/lib_ui/emoji_suggestions -I../Telegram/lib_base -I../Telegram/lib_rpl -I../Telegram/lib_crl -isystem /usr/include/qt5/QtCore/5.14.2 -isystem /usr/include/qt5/QtCore/5.14.2/QtCore -isystem /usr/include/qt5/QtGui/5.14.2 -isystem /usr/include/qt5/QtGui/5.14.2/QtGui -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtDBus -isystem /usr/share -isystem /usr/include/glib-2.0 -isystem /usr/lib64/glib-2.0/include -isystem /usr/include/libmount -isystem /usr/include/blkid -O2 -g1 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DNDEBUG   -fPIC -fno-strict-aliasing -pipe -Wall -W -Wno-unused-variable -Wno-unused-parameter -Wno-unused-function -Wno-switch -Wno-comment -Wno-unused-but-set-variable -Wno-missing-field-initializers -Wno-sign-compare -Wno-attributes -Wno-parentheses -Wno-stringop-overflow -Wno-maybe-uninitialized -Wno-error=class-memaccess -Wno-register -pthread -std=gnu++17 -Winvalid-pch -include /builddir/build/BUILD/tdesktop-2.5.9-full/x86_64-redhat-linux-gnu/Telegram/lib_ui/CMakeFiles/lib_ui.dir/cmake_pch.hxx -MD -MT Telegram/lib_ui/CMakeFiles/lib_ui.dir/ui/platform/linux/ui_utility_linux.cpp.o -MF Telegram/lib_ui/CMakeFiles/lib_ui.dir/ui/platform/linux/ui_utility_linux.cpp.o.d -o Telegram/lib_ui/CMakeFiles/lib_ui.dir/ui/platform/linux/ui_utility_linux.cpp.o -c ../Telegram/lib_ui/ui/platform/linux/ui_utility_linux.cpp
[334/857] /usr/bin/c++  -DDESKTOP_APP_DISABLE_CRASH_REPORTS -DDESKTOP_APP_DISABLE_WAYLAND_INTEGRATION -DDESKTOP_APP_USE_PACKAGED -DDESKTOP_APP_USE_PACKAGED_FONTS -DNDEBUG -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -ITelegram/lib_ui/lib_ui_autogen/include -ITelegram/lib_ui/gen -I../Telegram/lib_ui -I../Telegram/lib_ui/emoji_suggestions -I../Telegram/lib_base -I../Telegram/lib_rpl -I../Telegram/lib_crl -isystem /usr/include/qt5/QtCore/5.14.2 -isystem /usr/include/qt5/QtCore/5.14.2/QtCore -isystem /usr/include/qt5/QtGui/5.14.2 -isystem /usr/include/qt5/QtGui/5.14.2/QtGui -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtDBus -isystem /usr/share -isystem /usr/include/glib-2.0 -isystem /usr/lib64/glib-2.0/include -isystem /usr/include/libmount -isystem /usr/include/blkid -O2 -g1 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DNDEBUG   -fPIC -fno-strict-aliasing -pipe -Wall -W -Wno-unused-variable -Wno-unused-parameter -Wno-unused-function -Wno-switch -Wno-comment -Wno-unused-but-set-variable -Wno-missing-field-initializers -Wno-sign-compare -Wno-attributes -Wno-parentheses -Wno-stringop-overflow -Wno-maybe-uninitialized -Wno-error=class-memaccess -Wno-register -pthread -std=gnu++17 -Winvalid-pch -include /builddir/build/BUILD/tdesktop-2.5.9-full/x86_64-redhat-linux-gnu/Telegram/lib_ui/CMakeFiles/lib_ui.dir/cmake_pch.hxx -MD -MT Telegram/lib_ui/CMakeFiles/lib_ui.dir/ui/platform/ui_platform_window.cpp.o -MF Telegram/lib_ui/CMakeFiles/lib_ui.dir/ui/platform/ui_platform_window.cpp.o.d -o Telegram/lib_ui/CMakeFiles/lib_ui.dir/ui/platform/ui_platform_window.cpp.o -c ../Telegram/lib_ui/ui/platform/ui_platform_window.cpp
FAILED: Telegram/lib_ui/CMakeFiles/lib_ui.dir/ui/platform/ui_platform_window.cpp.o 
/usr/bin/c++  -DDESKTOP_APP_DISABLE_CRASH_REPORTS -DDESKTOP_APP_DISABLE_WAYLAND_INTEGRATION -DDESKTOP_APP_USE_PACKAGED -DDESKTOP_APP_USE_PACKAGED_FONTS -DNDEBUG -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -ITelegram/lib_ui/lib_ui_autogen/include -ITelegram/lib_ui/gen -I../Telegram/lib_ui -I../Telegram/lib_ui/emoji_suggestions -I../Telegram/lib_base -I../Telegram/lib_rpl -I../Telegram/lib_crl -isystem /usr/include/qt5/QtCore/5.14.2 -isystem /usr/include/qt5/QtCore/5.14.2/QtCore -isystem /usr/include/qt5/QtGui/5.14.2 -isystem /usr/include/qt5/QtGui/5.14.2/QtGui -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtDBus -isystem /usr/share -isystem /usr/include/glib-2.0 -isystem /usr/lib64/glib-2.0/include -isystem /usr/include/libmount -isystem /usr/include/blkid -O2 -g1 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DNDEBUG   -fPIC -fno-strict-aliasing -pipe -Wall -W -Wno-unused-variable -Wno-unused-parameter -Wno-unused-function -Wno-switch -Wno-comment -Wno-unused-but-set-variable -Wno-missing-field-initializers -Wno-sign-compare -Wno-attributes -Wno-parentheses -Wno-stringop-overflow -Wno-maybe-uninitialized -Wno-error=class-memaccess -Wno-register -pthread -std=gnu++17 -Winvalid-pch -include /builddir/build/BUILD/tdesktop-2.5.9-full/x86_64-redhat-linux-gnu/Telegram/lib_ui/CMakeFiles/lib_ui.dir/cmake_pch.hxx -MD -MT Telegram/lib_ui/CMakeFiles/lib_ui.dir/ui/platform/ui_platform_window.cpp.o -MF Telegram/lib_ui/CMakeFiles/lib_ui.dir/ui/platform/ui_platform_window.cpp.o.d -o Telegram/lib_ui/CMakeFiles/lib_ui.dir/ui/platform/ui_platform_window.cpp.o -c ../Telegram/lib_ui/ui/platform/ui_platform_window.cpp
../Telegram/lib_ui/ui/platform/ui_platform_window.cpp: In lambda function:
../Telegram/lib_ui/ui/platform/ui_platform_window.cpp:130:30: error: 'class QWindow' has no member named 'startSystemMove'
  130 |     _window->windowHandle()->startSystemMove();
      |                              ^~~~~~~~~~~~~~~
../Telegram/lib_ui/ui/platform/ui_platform_window.cpp: In lambda function:
../Telegram/lib_ui/ui/platform/ui_platform_window.cpp:207:31: error: 'class QWindow' has no member named 'startSystemResize'
  207 |     window()->windowHandle()->startSystemResize(edges);
      |                               ^~~~~~~~~~~~~~~~~
```

### Configuration
**Operating system:** Fedora 32

**Version of Telegram Desktop:** 2.5.9

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: build from sources

**Used theme**: n/a

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by xvitaly** [comment]
startSystemMove() and startSystemResize() are available only in Qt 5.15+.

**Comment by ilya-fedin** [comment]
Yeah, we discussed at the tdesktop contributions group and no one was agains deprecating the build on Qt<5.15. So, it's deprecated starting with 2.5.9.
